//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// vs_vtx_clr               0   xyz         0     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// sv_target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_input_ps linear v0.xyz
dcl_output o0.xyzw
//
// Initial variable locations:
//   v0.x <- vtx_clr.x; v0.y <- vtx_clr.y; v0.z <- vtx_clr.z; 
//   o0.x <- <main return value>.x; o0.y <- <main return value>.y; o0.z <- <main return value>.z; o0.w <- <main return value>.w
//
#line 3 "F:\projects\native_world\nw_gfx\src_hlsl\pxl_0.hlsl"
mov o0.xyz, v0.xyzx
mov o0.w, l(1.000000)
ret 
// Approximately 3 instruction slots used
