//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// coord                    0   xyz         0     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// color                    0   xyz         0     NONE   float   xyz 
// SV_Position              0   xyzw        1      POS   float   xyzw
//
vs_4_0
dcl_input v0.xyz
dcl_output o0.xyz
dcl_output_siv o1.xyzw, position
dcl_temps 2
//
// Initial variable locations:
//   v0.x <- atb_vtxCrd.x; v0.y <- atb_vtxCrd.y; v0.z <- atb_vtxCrd.z; 
//   o1.x <- <main return value>.vtxCrd.x; o1.y <- <main return value>.vtxCrd.y; o1.z <- <main return value>.vtxCrd.z; o1.w <- <main return value>.vtxCrd.w; 
//   o0.x <- <main return value>.vtxClr.x; o0.y <- <main return value>.vtxClr.y; o0.z <- <main return value>.vtxClr.z
//
#line 14 "D:\dev\native_world\nw_gfx\src_hlsl\shd_0_vtx.hlsl"
mov r0.xyz, v0.xyzx  // r0.x <- vs_out.vtxCrd.x; r0.y <- vs_out.vtxCrd.y; r0.z <- vs_out.vtxCrd.z
mov r0.w, l(1.000000)  // r0.w <- vs_out.vtxCrd.w

#line 15
mov r1.xyz, v0.xyzx  // r1.x <- vs_out.vtxClr.x; r1.y <- vs_out.vtxClr.y; r1.z <- vs_out.vtxClr.z

#line 16
mov o1.xyzw, r0.xyzw
mov o0.xyz, r1.xyzx
ret 
// Approximately 6 instruction slots used
