//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbf_transform
// {
//
//   row_major float4x4 cst_matModel;   // Offset:    0 Size:    64
//   row_major float4x4 cst_matView;    // Offset:   64 Size:    64
//   row_major float4x4 cst_matProj;    // Offset:  128 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbf_transform                     cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// vtx_crd                  0   xyz         0     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// vs_vtx_clr               0   xyz         0     NONE   float   xyz 
// sv_position              0   xyzw        1      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[12], immediateIndexed
dcl_input v0.xyz
dcl_output o0.xyz
dcl_output_siv o1.xyzw, position
dcl_temps 3
//
// Initial variable locations:
//   v0.x <- atb_vtx_crd.x; v0.y <- atb_vtx_crd.y; v0.z <- atb_vtx_crd.z; 
//   o1.x <- <main return value>.vtx_crd.x; o1.y <- <main return value>.vtx_crd.y; o1.z <- <main return value>.vtx_crd.z; o1.w <- <main return value>.vtx_crd.w; 
//   o0.x <- <main return value>.vtx_clr.x; o0.y <- <main return value>.vtx_clr.y; o0.z <- <main return value>.vtx_clr.z
//
<<<<<<< HEAD
#line 15 "F:\projects\native_world\nw_gfx\src_hlsl\vtx_0.hlsl"
mov r0.xyz, v0.xyzx  // r0.x <- vso.vtxCrd.x; r0.y <- vso.vtxCrd.y; r0.z <- vso.vtxCrd.z
mov r0.w, l(1.000000)  // r0.w <- vso.vtxCrd.w
=======
#line 15 "D:\dev\native_world\nw_gfx\src_hlsl\vtx_0.hlsl"
mov r0.xyz, v0.xyzx  // r0.x <- vso.vtx_crd.x; r0.y <- vso.vtx_crd.y; r0.z <- vso.vtx_crd.z
mov r0.w, l(1.000000)  // r0.w <- vso.vtx_crd.w
>>>>>>> 430af4e607072ef3493e27858bfaef3d92e36416

#line 16
mul r1.xyzw, r0.xxxx, cb0[0].xyzw
mul r2.xyzw, r0.yyyy, cb0[1].xyzw
add r1.xyzw, r1.xyzw, r2.xyzw
mul r2.xyzw, r0.zzzz, cb0[2].xyzw
add r1.xyzw, r1.xyzw, r2.xyzw
mul r0.xyzw, r0.wwww, cb0[3].xyzw
add r0.xyzw, r0.xyzw, r1.xyzw  // r0.x <- vso.vtx_crd.x; r0.y <- vso.vtx_crd.y; r0.z <- vso.vtx_crd.z; r0.w <- vso.vtx_crd.w

#line 17
mul r1.xyzw, r0.xxxx, cb0[4].xyzw
mul r2.xyzw, r0.yyyy, cb0[5].xyzw
add r1.xyzw, r1.xyzw, r2.xyzw
mul r2.xyzw, r0.zzzz, cb0[6].xyzw
add r1.xyzw, r1.xyzw, r2.xyzw
mul r0.xyzw, r0.wwww, cb0[7].xyzw
add r0.xyzw, r0.xyzw, r1.xyzw  // r0.x <- vso.vtx_crd.x; r0.y <- vso.vtx_crd.y; r0.z <- vso.vtx_crd.z; r0.w <- vso.vtx_crd.w

#line 18
mul r1.xyzw, r0.xxxx, cb0[8].xyzw
mul r2.xyzw, r0.yyyy, cb0[9].xyzw
add r1.xyzw, r1.xyzw, r2.xyzw
mul r2.xyzw, r0.zzzz, cb0[10].xyzw
add r1.xyzw, r1.xyzw, r2.xyzw
mul r0.xyzw, r0.wwww, cb0[11].xyzw
add r0.xyzw, r0.xyzw, r1.xyzw  // r0.x <- vso.vtx_crd.x; r0.y <- vso.vtx_crd.y; r0.z <- vso.vtx_crd.z; r0.w <- vso.vtx_crd.w

#line 19
mov r1.xyz, v0.xyzx  // r1.x <- vso.vtx_clr.x; r1.y <- vso.vtx_clr.y; r1.z <- vso.vtx_clr.z

#line 20
mov o1.xyzw, r0.xyzw
mov o0.xyz, r1.xyzx
ret 
// Approximately 27 instruction slots used
