//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbf_transform
// {
//
//   float4x4 cst_matModel;             // Offset:    0 Size:    64
//   float4x4 cst_matView;              // Offset:   64 Size:    64
//   float4x4 cst_matProj;              // Offset:  128 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbf_transform                     cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// vtx_crd                  0   xyz         0     NONE   float   xyz 
// tex_crd                  0   xy          1     NONE   float   xy  
// nrm_crd                  0   xyz         2     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// vs_tex_crd               0   xy          0     NONE   float   xy  
// vs_nrm_crd               0   xyz         1     NONE   float   xyz 
// sv_position              0   xyzw        2      POS   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[12], immediateIndexed
dcl_input v0.xyz
dcl_input v1.xy
dcl_input v2.xyz
dcl_output o0.xy
dcl_output o1.xyz
dcl_output_siv o2.xyzw, position
dcl_temps 4
//
// Initial variable locations:
//   v0.x <- atb_vtx_crd.x; v0.y <- atb_vtx_crd.y; v0.z <- atb_vtx_crd.z; 
//   v1.x <- atb_tex_crd.x; v1.y <- atb_tex_crd.y; 
//   v2.x <- atb_nrm_crd.x; v2.y <- atb_nrm_crd.y; v2.z <- atb_nrm_crd.z; 
//   o2.x <- <main return value>.vtx_crd.x; o2.y <- <main return value>.vtx_crd.y; o2.z <- <main return value>.vtx_crd.z; o2.w <- <main return value>.vtx_crd.w; 
//   o1.x <- <main return value>.nrm_crd.x; o1.y <- <main return value>.nrm_crd.y; o1.z <- <main return value>.nrm_crd.z; 
//   o0.x <- <main return value>.tex_crd.x; o0.y <- <main return value>.tex_crd.y
//
<<<<<<< HEAD
#line 15 "F:\projects\native_world\nw_gfx\src_hlsl\vtx_3d_default.hlsl"
mov r0.xy, v1.xyxx  // r0.x <- vso.texCrd.x; r0.y <- vso.texCrd.y
=======
#line 15 "D:\dev\native_world\nw_gfx\src_hlsl\vtx_3d_default.hlsl"
mov r0.xy, v1.xyxx  // r0.x <- vso.tex_crd.x; r0.y <- vso.tex_crd.y
>>>>>>> 430af4e607072ef3493e27858bfaef3d92e36416

#line 16
mov r1.xyz, v2.xyzx  // r1.x <- vso.nrm_crd.x; r1.y <- vso.nrm_crd.y; r1.z <- vso.nrm_crd.z

#line 17
mov r2.xyz, v0.xyzx  // r2.x <- vso.vtx_crd.x; r2.y <- vso.vtx_crd.y; r2.z <- vso.vtx_crd.z
mov r2.w, l(1.000000)  // r2.w <- vso.vtx_crd.w

#line 18
dp4 r3.x, r2.xyzw, cb0[0].xyzw  // r3.x <- vso.vtx_crd.x
dp4 r3.y, r2.xyzw, cb0[1].xyzw  // r3.y <- vso.vtx_crd.y
dp4 r3.z, r2.xyzw, cb0[2].xyzw  // r3.z <- vso.vtx_crd.z
dp4 r3.w, r2.xyzw, cb0[3].xyzw  // r3.w <- vso.vtx_crd.w

#line 19
dp4 r2.x, r3.xyzw, cb0[4].xyzw  // r2.x <- vso.vtx_crd.x
dp4 r2.y, r3.xyzw, cb0[5].xyzw  // r2.y <- vso.vtx_crd.y
dp4 r2.z, r3.xyzw, cb0[6].xyzw  // r2.z <- vso.vtx_crd.z
dp4 r2.w, r3.xyzw, cb0[7].xyzw  // r2.w <- vso.vtx_crd.w

#line 20
dp4 r3.x, r2.xyzw, cb0[8].xyzw  // r3.x <- vso.vtx_crd.x
dp4 r3.y, r2.xyzw, cb0[9].xyzw  // r3.y <- vso.vtx_crd.y
dp4 r3.z, r2.xyzw, cb0[10].xyzw  // r3.z <- vso.vtx_crd.z
dp4 r3.w, r2.xyzw, cb0[11].xyzw  // r3.w <- vso.vtx_crd.w

#line 21
mov o2.xyzw, r3.xyzw
mov o1.xyz, r1.xyzx
mov o0.xy, r0.xyxx
ret 
// Approximately 20 instruction slots used
