# GNU Make project makefile autogenerated by Premake

ifndef config
  config=work_win64
endif

ifndef verbose
  SILENT = @
endif

.PHONY: clean prebuild prelink

ifeq ($(config),work_win64)
  ifeq ($(origin CC), default)
    CC = F:\dev\gcc\bin\gcc.exe
  endif
  ifeq ($(origin CXX), default)
    CXX = F:\dev\gcc\bin\g++.exe
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  RESCOMP = default
  TARGETDIR = bin_cxx
  TARGET = $(TARGETDIR)/nc_gfx
  OBJDIR = bin_cxx/win64/work
  DEFINES +=
  INCLUDES += -Isrc_cxx
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -ffloat-store -g -w -std=c99 -fpermissive
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -ffloat-store -g -w -fpermissive
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../nc_cfg/bin_cxx/nc_cfg.lib ../nc_lib/bin_cxx/nc_lib.lib
  LDDEPS += ../nc_cfg/bin_cxx/nc_cfg.lib ../nc_lib/bin_cxx/nc_lib.lib
  ALL_LDFLAGS += $(LDFLAGS) -L../nc_cfg -L../nc_lib -L../nc_mem -L../nc_iop -L/usr/lib64 -m64
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

ifeq ($(config),game_win64)
  ifeq ($(origin CC), default)
    CC = F:\dev\gcc\bin\gcc.exe
  endif
  ifeq ($(origin CXX), default)
    CXX = F:\dev\gcc\bin\g++.exe
  endif
  ifeq ($(origin AR), default)
    AR = ar
  endif
  RESCOMP = default
  TARGETDIR = bin_cxx
  TARGET = $(TARGETDIR)/nc_gfx
  OBJDIR = bin_cxx/win64/game
  DEFINES +=
  INCLUDES += -Isrc_cxx
  FORCE_INCLUDE +=
  ALL_CPPFLAGS += $(CPPFLAGS) -MMD -MP $(DEFINES) $(INCLUDES)
  ALL_CFLAGS += $(CFLAGS) $(ALL_CPPFLAGS) -m64 -w -std=c99 -fpermissive
  ALL_CXXFLAGS += $(CXXFLAGS) $(ALL_CPPFLAGS) -m64 -w -fpermissive
  ALL_RESFLAGS += $(RESFLAGS) $(DEFINES) $(INCLUDES)
  LIBS += ../nc_cfg/bin_cxx/nc_cfg.lib ../nc_lib/bin_cxx/nc_lib.lib
  LDDEPS += ../nc_cfg/bin_cxx/nc_cfg.lib ../nc_lib/bin_cxx/nc_lib.lib
  ALL_LDFLAGS += $(LDFLAGS) -L../nc_cfg -L../nc_lib -L../nc_mem -L../nc_iop -L/usr/lib64 -m64 -s
  LINKCMD = $(CC) -o "$@" $(OBJECTS) $(RESOURCES) $(ALL_LDFLAGS) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
all: prebuild prelink $(TARGET)
	@:

endif

OBJECTS := \
	$(OBJDIR)/nc_gfx_entry.o \
	$(OBJDIR)/nc_gfx_pch.o \

RESOURCES := \

CUSTOMFILES := \

SHELLTYPE := posix
ifeq (.exe,$(findstring .exe,$(ComSpec)))
	SHELLTYPE := msdos
endif

$(TARGET): $(GCH) ${CUSTOMFILES} $(OBJECTS) $(LDDEPS) $(RESOURCES) | $(TARGETDIR)
	@echo Linking nc_gfx
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(CUSTOMFILES): | $(OBJDIR)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning nc_gfx
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(OBJECTS): $(GCH) $(PCH) | $(OBJDIR)
$(GCH): $(PCH) | $(OBJDIR)
	@echo $(notdir $<)
	$(SILENT) $(CC) -x c-header $(ALL_CFLAGS) -o "$@" -MF "$(@:%.gch=%.d)" -c "$<"
else
$(OBJECTS): | $(OBJDIR)
endif

$(OBJDIR)/nc_gfx_entry.o: src_cxx/nc_gfx_entry.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
$(OBJDIR)/nc_gfx_pch.o: src_cxx/nc_gfx_pch.cxx
	@echo $(notdir $<)
ifeq ($(config),work_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif
ifeq ($(config),game_win64)
	$(SILENT) $(CC) $(ALL_CFLAGS) $(FORCE_INCLUDE) -o "$@" -MF "$(@:%.o=%.d)" -c "$<"
endif

-include $(OBJECTS:%.o=%.d)
ifneq (,$(PCH))
  -include $(OBJDIR)/$(notdir $(PCH)).d
endif