#include <nwg_pch.hpp>
#include "nwg_ogl_v2.h"
#include "nwg_ogl_loader.h"
namespace NWG
{
	void OglLoadV2() {
#if (defined GL_VERSION_2_0)
		OglBlendEquationSeparate = (PFNGLBLENDEQUATIONSEPARATEPROC)OglGetProc("glBlendEquationSeparate");
		OglDrawBuffers = (PFNGLDRAWBUFFERSPROC)OglGetProc("glDrawBuffers");
		OglStencilOpSeparate = (PFNGLSTENCILOPSEPARATEPROC)OglGetProc("glStencilOpSeparate");
		OglStencilFuncSeparate = (PFNGLSTENCILFUNCSEPARATEPROC)OglGetProc("glStencilFuncSeparate");
		OglStencilMaskSeparate = (PFNGLSTENCILMASKSEPARATEPROC)OglGetProc("glStencilMaskSeparate");
		OglAttachShader = (PFNGLATTACHSHADERPROC)OglGetProc("glAttachShader");
		OglBindAttribLocation = (PFNGLBINDATTRIBLOCATIONPROC)OglGetProc("glBindAttribLocation");
		OglCompileShader = (PFNGLCOMPILESHADERPROC)OglGetProc("glCompileShader");
		OglCreateProgram = (PFNGLCREATEPROGRAMPROC)OglGetProc("glCreateProgram");
		OglCreateShader = (PFNGLCREATESHADERPROC)OglGetProc("glCreateShader");
		OglDeleteProgram = (PFNGLDELETEPROGRAMPROC)OglGetProc("glDeleteProgram");
		OglDeleteShader = (PFNGLDELETESHADERPROC)OglGetProc("glDeleteShader");
		OglDetachShader = (PFNGLDETACHSHADERPROC)OglGetProc("glDetachShader");
		OglDisableVertexAttribArray = (PFNGLDISABLEVERTEXATTRIBARRAYPROC)OglGetProc("glDisableVertexAttribArray");
		OglEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC)OglGetProc("glEnableVertexAttribArray");
		OglGetActiveAttrib = (PFNGLGETACTIVEATTRIBPROC)OglGetProc("glGetActiveAttrib");
		OglGetActiveUniform = (PFNGLGETACTIVEUNIFORMPROC)OglGetProc("glGetActiveUniform");
		OglGetAttachedShaders = (PFNGLGETATTACHEDSHADERSPROC)OglGetProc("glGetAttachedShaders");
		OglGetAttribLocation = (PFNGLGETATTRIBLOCATIONPROC)OglGetProc("glGetAttribLocation");
		OglGetProgramiv = (PFNGLGETPROGRAMIVPROC)OglGetProc("glGetProgramiv");
		OglGetProgramInfoLog = (PFNGLGETPROGRAMINFOLOGPROC)OglGetProc("glGetProgramInfoLog");
		OglGetShaderiv = (PFNGLGETSHADERIVPROC)OglGetProc("glGetShaderiv");
		OglGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC)OglGetProc("glGetShaderInfoLog");
		OglGetShaderSource = (PFNGLGETSHADERSOURCEPROC)OglGetProc("glGetShaderSource");
		OglGetUniformLocation = (PFNGLGETUNIFORMLOCATIONPROC)OglGetProc("glGetUniformLocation");
		OglGetUniformfv = (PFNGLGETUNIFORMFVPROC)OglGetProc("glGetUniformfv");
		OglGetUniformiv = (PFNGLGETUNIFORMIVPROC)OglGetProc("glGetUniformiv");
		OglGetVertexAttribdv = (PFNGLGETVERTEXATTRIBDVPROC)OglGetProc("glGetVertexAttribdv");
		OglGetVertexAttribfv = (PFNGLGETVERTEXATTRIBFVPROC)OglGetProc("glGetVertexAttribfv");
		OglGetVertexAttribiv = (PFNGLGETVERTEXATTRIBIVPROC)OglGetProc("glGetVertexAttribiv");
		OglGetVertexAttribPointerv = (PFNGLGETVERTEXATTRIBPOINTERVPROC)OglGetProc("glGetVertexAttribPointerv");
		OglIsProgram = (PFNGLISPROGRAMPROC)OglGetProc("glIsProgram");
		OglIsShader = (PFNGLISSHADERPROC)OglGetProc("glIsShader");
		OglLinkProgram = (PFNGLLINKPROGRAMPROC)OglGetProc("glLinkProgram");
		OglShaderSource = (PFNGLSHADERSOURCEPROC)OglGetProc("glShaderSource");
		OglUseProgram = (PFNGLUSEPROGRAMPROC)OglGetProc("glUseProgram");
		OglUniform1f = (PFNGLUNIFORM1FPROC)OglGetProc("glUniform1f");
		OglUniform2f = (PFNGLUNIFORM2FPROC)OglGetProc("glUniform2f");
		OglUniform3f = (PFNGLUNIFORM3FPROC)OglGetProc("glUniform3f");
		OglUniform4f = (PFNGLUNIFORM4FPROC)OglGetProc("glUniform4f");
		OglUniform1i = (PFNGLUNIFORM1IPROC)OglGetProc("glUniform1i");
		OglUniform2i = (PFNGLUNIFORM2IPROC)OglGetProc("glUniform2i");
		OglUniform3i = (PFNGLUNIFORM3IPROC)OglGetProc("glUniform3i");
		OglUniform4i = (PFNGLUNIFORM4IPROC)OglGetProc("glUniform4i");
		OglUniform1fv = (PFNGLUNIFORM1FVPROC)OglGetProc("glUniform1fv");
		OglUniform2fv = (PFNGLUNIFORM2FVPROC)OglGetProc("glUniform2fv");
		OglUniform3fv = (PFNGLUNIFORM3FVPROC)OglGetProc("glUniform3fv");
		OglUniform4fv = (PFNGLUNIFORM4FVPROC)OglGetProc("glUniform4fv");
		OglUniform1iv = (PFNGLUNIFORM1IVPROC)OglGetProc("glUniform1iv");
		OglUniform2iv = (PFNGLUNIFORM2IVPROC)OglGetProc("glUniform2iv");
		OglUniform3iv = (PFNGLUNIFORM3IVPROC)OglGetProc("glUniform3iv");
		OglUniform4iv = (PFNGLUNIFORM4IVPROC)OglGetProc("glUniform4iv");
		OglUniformMatrix2fv = (PFNGLUNIFORMMATRIX2FVPROC)OglGetProc("glUniformMatrix2fv");
		OglUniformMatrix3fv = (PFNGLUNIFORMMATRIX3FVPROC)OglGetProc("glUniformMatrix3fv");
		OglUniformMatrix4fv = (PFNGLUNIFORMMATRIX4FVPROC)OglGetProc("glUniformMatrix4fv");
		OglValidateProgram = (PFNGLVALIDATEPROGRAMPROC)OglGetProc("glValidateProgram");
		OglVertexAttrib1d = (PFNGLVERTEXATTRIB1DPROC)OglGetProc("glVertexAttrib1d");
		OglVertexAttrib1dv = (PFNGLVERTEXATTRIB1DVPROC)OglGetProc("glVertexAttrib1dv");
		OglVertexAttrib1f = (PFNGLVERTEXATTRIB1FPROC)OglGetProc("glVertexAttrib1f");
		OglVertexAttrib1fv = (PFNGLVERTEXATTRIB1FVPROC)OglGetProc("glVertexAttrib1fv");
		OglVertexAttrib1s = (PFNGLVERTEXATTRIB1SPROC)OglGetProc("glVertexAttrib1s");
		OglVertexAttrib1sv = (PFNGLVERTEXATTRIB1SVPROC)OglGetProc("glVertexAttrib1sv");
		OglVertexAttrib2d = (PFNGLVERTEXATTRIB2DPROC)OglGetProc("glVertexAttrib2d");
		OglVertexAttrib2dv = (PFNGLVERTEXATTRIB2DVPROC)OglGetProc("glVertexAttrib2dv");
		OglVertexAttrib2f = (PFNGLVERTEXATTRIB2FPROC)OglGetProc("glVertexAttrib2f");
		OglVertexAttrib2fv = (PFNGLVERTEXATTRIB2FVPROC)OglGetProc("glVertexAttrib2fv");
		OglVertexAttrib2s = (PFNGLVERTEXATTRIB2SPROC)OglGetProc("glVertexAttrib2s");
		OglVertexAttrib2sv = (PFNGLVERTEXATTRIB2SVPROC)OglGetProc("glVertexAttrib2sv");
		OglVertexAttrib3d = (PFNGLVERTEXATTRIB3DPROC)OglGetProc("glVertexAttrib3d");
		OglVertexAttrib3dv = (PFNGLVERTEXATTRIB3DVPROC)OglGetProc("glVertexAttrib3dv");
		OglVertexAttrib3f = (PFNGLVERTEXATTRIB3FPROC)OglGetProc("glVertexAttrib3f");
		OglVertexAttrib3fv = (PFNGLVERTEXATTRIB3FVPROC)OglGetProc("glVertexAttrib3fv");
		OglVertexAttrib3s = (PFNGLVERTEXATTRIB3SPROC)OglGetProc("glVertexAttrib3s");
		OglVertexAttrib3sv = (PFNGLVERTEXATTRIB3SVPROC)OglGetProc("glVertexAttrib3sv");
		OglVertexAttrib4Nbv = (PFNGLVERTEXATTRIB4NBVPROC)OglGetProc("glVertexAttrib4Nbv");
		OglVertexAttrib4Niv = (PFNGLVERTEXATTRIB4NIVPROC)OglGetProc("glVertexAttrib4Niv");
		OglVertexAttrib4Nsv = (PFNGLVERTEXATTRIB4NSVPROC)OglGetProc("glVertexAttrib4Nsv");
		OglVertexAttrib4Nub = (PFNGLVERTEXATTRIB4NUBPROC)OglGetProc("glVertexAttrib4Nub");
		OglVertexAttrib4Nubv = (PFNGLVERTEXATTRIB4NUBVPROC)OglGetProc("glVertexAttrib4Nubv");
		OglVertexAttrib4Nuiv = (PFNGLVERTEXATTRIB4NUIVPROC)OglGetProc("glVertexAttrib4Nuiv");
		OglVertexAttrib4Nusv = (PFNGLVERTEXATTRIB4NUSVPROC)OglGetProc("glVertexAttrib4Nusv");
		OglVertexAttrib4bv = (PFNGLVERTEXATTRIB4BVPROC)OglGetProc("glVertexAttrib4bv");
		OglVertexAttrib4d = (PFNGLVERTEXATTRIB4DPROC)OglGetProc("glVertexAttrib4d");
		OglVertexAttrib4dv = (PFNGLVERTEXATTRIB4DVPROC)OglGetProc("glVertexAttrib4dv");
		OglVertexAttrib4f = (PFNGLVERTEXATTRIB4FPROC)OglGetProc("glVertexAttrib4f");
		OglVertexAttrib4fv = (PFNGLVERTEXATTRIB4FVPROC)OglGetProc("glVertexAttrib4fv");
		OglVertexAttrib4iv = (PFNGLVERTEXATTRIB4IVPROC)OglGetProc("glVertexAttrib4iv");
		OglVertexAttrib4s = (PFNGLVERTEXATTRIB4SPROC)OglGetProc("glVertexAttrib4s");
		OglVertexAttrib4sv = (PFNGLVERTEXATTRIB4SVPROC)OglGetProc("glVertexAttrib4sv");
		OglVertexAttrib4ubv = (PFNGLVERTEXATTRIB4UBVPROC)OglGetProc("glVertexAttrib4ubv");
		OglVertexAttrib4uiv = (PFNGLVERTEXATTRIB4UIVPROC)OglGetProc("glVertexAttrib4uiv");
		OglVertexAttrib4usv = (PFNGLVERTEXATTRIB4USVPROC)OglGetProc("glVertexAttrib4usv");
		OglVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC)OglGetProc("glVertexAttribPointer");
#endif	// GL_VERSION_2_0
#if (defined GL_VERSION_2_1)
		OglUniformMatrix2x3fv = (PFNGLUNIFORMMATRIX2X3FVPROC)OglGetProc("glUniformMatrix2x3fv");
		OglUniformMatrix3x2fv = (PFNGLUNIFORMMATRIX3X2FVPROC)OglGetProc("glUniformMatrix3x2fv");
		OglUniformMatrix2x4fv = (PFNGLUNIFORMMATRIX2X4FVPROC)OglGetProc("glUniformMatrix2x4fv");
		OglUniformMatrix4x2fv = (PFNGLUNIFORMMATRIX4X2FVPROC)OglGetProc("glUniformMatrix4x2fv");
		OglUniformMatrix3x4fv = (PFNGLUNIFORMMATRIX3X4FVPROC)OglGetProc("glUniformMatrix3x4fv");
		OglUniformMatrix4x3fv = (PFNGLUNIFORMMATRIX4X3FVPROC)OglGetProc("glUniformMatrix4x3fv");
#endif	// GL_VERSION_2_1
	}
}
#ifdef GL_VERSION_2_0
PFNGLBLENDEQUATIONSEPARATEPROC OglBlendEquationSeparate;
PFNGLDRAWBUFFERSPROC OglDrawBuffers;
PFNGLSTENCILOPSEPARATEPROC OglStencilOpSeparate;
PFNGLSTENCILFUNCSEPARATEPROC OglStencilFuncSeparate;
PFNGLSTENCILMASKSEPARATEPROC OglStencilMaskSeparate;
PFNGLATTACHSHADERPROC OglAttachShader;
PFNGLBINDATTRIBLOCATIONPROC OglBindAttribLocation;
PFNGLCOMPILESHADERPROC OglCompileShader;
PFNGLCREATEPROGRAMPROC OglCreateProgram;
PFNGLCREATESHADERPROC OglCreateShader;
PFNGLDELETEPROGRAMPROC OglDeleteProgram;
PFNGLDELETESHADERPROC OglDeleteShader;
PFNGLDETACHSHADERPROC OglDetachShader;
PFNGLDISABLEVERTEXATTRIBARRAYPROC OglDisableVertexAttribArray;
PFNGLENABLEVERTEXATTRIBARRAYPROC OglEnableVertexAttribArray;
PFNGLGETACTIVEATTRIBPROC OglGetActiveAttrib;
PFNGLGETACTIVEUNIFORMPROC OglGetActiveUniform;
PFNGLGETATTACHEDSHADERSPROC OglGetAttachedShaders;
PFNGLGETATTRIBLOCATIONPROC OglGetAttribLocation;
PFNGLGETPROGRAMIVPROC OglGetProgramiv = NULL;
PFNGLGETPROGRAMINFOLOGPROC OglGetProgramInfoLog = NULL;
PFNGLGETSHADERIVPROC OglGetShaderiv = NULL;
PFNGLGETSHADERINFOLOGPROC OglGetShaderInfoLog = NULL;
PFNGLGETSHADERSOURCEPROC OglGetShaderSource;
PFNGLGETUNIFORMLOCATIONPROC OglGetUniformLocation;
PFNGLGETUNIFORMFVPROC OglGetUniformfv;
PFNGLGETUNIFORMIVPROC OglGetUniformiv;
PFNGLGETVERTEXATTRIBDVPROC OglGetVertexAttribdv;
PFNGLGETVERTEXATTRIBFVPROC OglGetVertexAttribfv;
PFNGLGETVERTEXATTRIBIVPROC OglGetVertexAttribiv;
PFNGLGETVERTEXATTRIBPOINTERVPROC OglGetVertexAttribPointerv;
PFNGLISPROGRAMPROC OglIsProgram;
PFNGLISSHADERPROC OglIsShader;
PFNGLLINKPROGRAMPROC OglLinkProgram;
PFNGLSHADERSOURCEPROC OglShaderSource;
PFNGLUSEPROGRAMPROC OglUseProgram;
PFNGLUNIFORM1FPROC OglUniform1f;
PFNGLUNIFORM2FPROC OglUniform2f;
PFNGLUNIFORM3FPROC OglUniform3f;
PFNGLUNIFORM4FPROC OglUniform4f;
PFNGLUNIFORM1IPROC OglUniform1i;
PFNGLUNIFORM2IPROC OglUniform2i;
PFNGLUNIFORM3IPROC OglUniform3i;
PFNGLUNIFORM4IPROC OglUniform4i;
PFNGLUNIFORM1FVPROC OglUniform1fv;
PFNGLUNIFORM2FVPROC OglUniform2fv;
PFNGLUNIFORM3FVPROC OglUniform3fv;
PFNGLUNIFORM4FVPROC OglUniform4fv;
PFNGLUNIFORM1IVPROC OglUniform1iv;
PFNGLUNIFORM2IVPROC OglUniform2iv;
PFNGLUNIFORM3IVPROC OglUniform3iv;
PFNGLUNIFORM4IVPROC OglUniform4iv;
PFNGLUNIFORMMATRIX2FVPROC OglUniformMatrix2fv;
PFNGLUNIFORMMATRIX3FVPROC OglUniformMatrix3fv;
PFNGLUNIFORMMATRIX4FVPROC OglUniformMatrix4fv;
PFNGLVALIDATEPROGRAMPROC OglValidateProgram;
PFNGLVERTEXATTRIB1DPROC OglVertexAttrib1d;
PFNGLVERTEXATTRIB1DVPROC OglVertexAttrib1dv;
PFNGLVERTEXATTRIB1FPROC OglVertexAttrib1f;
PFNGLVERTEXATTRIB1FVPROC OglVertexAttrib1fv;
PFNGLVERTEXATTRIB1SPROC OglVertexAttrib1s;
PFNGLVERTEXATTRIB1SVPROC OglVertexAttrib1sv;
PFNGLVERTEXATTRIB2DPROC OglVertexAttrib2d;
PFNGLVERTEXATTRIB2DVPROC OglVertexAttrib2dv;
PFNGLVERTEXATTRIB2FPROC OglVertexAttrib2f;
PFNGLVERTEXATTRIB2FVPROC OglVertexAttrib2fv;
PFNGLVERTEXATTRIB2SPROC OglVertexAttrib2s;
PFNGLVERTEXATTRIB2SVPROC OglVertexAttrib2sv;
PFNGLVERTEXATTRIB3DPROC OglVertexAttrib3d;
PFNGLVERTEXATTRIB3DVPROC OglVertexAttrib3dv;
PFNGLVERTEXATTRIB3FPROC OglVertexAttrib3f;
PFNGLVERTEXATTRIB3FVPROC OglVertexAttrib3fv;
PFNGLVERTEXATTRIB3SPROC OglVertexAttrib3s;
PFNGLVERTEXATTRIB3SVPROC OglVertexAttrib3sv;
PFNGLVERTEXATTRIB4NBVPROC OglVertexAttrib4Nbv;
PFNGLVERTEXATTRIB4NIVPROC OglVertexAttrib4Niv;
PFNGLVERTEXATTRIB4NSVPROC OglVertexAttrib4Nsv;
PFNGLVERTEXATTRIB4NUBPROC OglVertexAttrib4Nub;
PFNGLVERTEXATTRIB4NUBVPROC OglVertexAttrib4Nubv;
PFNGLVERTEXATTRIB4NUIVPROC OglVertexAttrib4Nuiv;
PFNGLVERTEXATTRIB4NUSVPROC OglVertexAttrib4Nusv;
PFNGLVERTEXATTRIB4BVPROC OglVertexAttrib4bv;
PFNGLVERTEXATTRIB4DPROC OglVertexAttrib4d;
PFNGLVERTEXATTRIB4DVPROC OglVertexAttrib4dv;
PFNGLVERTEXATTRIB4FPROC OglVertexAttrib4f;
PFNGLVERTEXATTRIB4FVPROC OglVertexAttrib4fv;
PFNGLVERTEXATTRIB4IVPROC OglVertexAttrib4iv;
PFNGLVERTEXATTRIB4SPROC OglVertexAttrib4s;
PFNGLVERTEXATTRIB4SVPROC OglVertexAttrib4sv;
PFNGLVERTEXATTRIB4UBVPROC OglVertexAttrib4ubv;
PFNGLVERTEXATTRIB4UIVPROC OglVertexAttrib4uiv;
PFNGLVERTEXATTRIB4USVPROC OglVertexAttrib4usv;
PFNGLVERTEXATTRIBPOINTERPROC OglVertexAttribPointer;
#endif	// GL_VERSION_2_0

#ifdef GL_VERSION_2_1
PFNGLUNIFORMMATRIX2X3FVPROC OglUniformMatrix2x3fv;
PFNGLUNIFORMMATRIX3X2FVPROC OglUniformMatrix3x2fv;
PFNGLUNIFORMMATRIX2X4FVPROC OglUniformMatrix2x4fv;
PFNGLUNIFORMMATRIX4X2FVPROC OglUniformMatrix4x2fv;
PFNGLUNIFORMMATRIX3X4FVPROC OglUniformMatrix3x4fv;
PFNGLUNIFORMMATRIX4X3FVPROC OglUniformMatrix4x3fv;
#endif	// GL_VERSION_2_1