#include <nwg_pch.hpp>
#include "nwg_ogl_arb.h"
#include "nwg_ogl_loader.h"
namespace NWG
{
	void OglLoadArb()
	{
#if (defined NWG_OGL_ARB_H)
		OglIsRenderbuffer = (PFNGLISRENDERBUFFERPROC)OglGetProc("glIsRenderbuffer");
		OglBindRenderbuffer = (PFNGLBINDRENDERBUFFERPROC)OglGetProc("glBindRenderbuffer");
		OglDeleteRenderbuffers = (PFNGLDELETERENDERBUFFERSPROC)OglGetProc("glDeleteRenderbuffers");
		OglGenRenderbuffers = (PFNGLGENRENDERBUFFERSPROC)OglGetProc("glGenRenderbuffers");
		OglRenderbufferStorage = (PFNGLRENDERBUFFERSTORAGEPROC)OglGetProc("glRenderbufferStorage");
		OglGetRenderbufferParameteriv = (PFNGLGETRENDERBUFFERPARAMETERIVPROC)OglGetProc("glGetRenderbufferParameteriv");
		OglIsFramebuffer = (PFNGLISFRAMEBUFFERPROC)OglGetProc("glIsFramebuffer");
		OglBindFramebuffer = (PFNGLBINDFRAMEBUFFERPROC)OglGetProc("glBindFramebuffer");
		OglDeleteFramebuffers = (PFNGLDELETEFRAMEBUFFERSPROC)OglGetProc("glDeleteFramebuffers");
		OglGenFramebuffers = (PFNGLGENFRAMEBUFFERSPROC)OglGetProc("glGenFramebuffers");
		OglCheckFramebufferStatus = (PFNGLCHECKFRAMEBUFFERSTATUSPROC)OglGetProc("glCheckFramebufferStatus");
		OglFramebufferTexture1D = (PFNGLFRAMEBUFFERTEXTURE1DPROC)OglGetProc("glFramebufferTexture1D");
		OglFramebufferTexture2D = (PFNGLFRAMEBUFFERTEXTURE2DPROC)OglGetProc("glFramebufferTexture2D");
		OglFramebufferTexture3D = (PFNGLFRAMEBUFFERTEXTURE3DPROC)OglGetProc("glFramebufferTexture3D");
		OglFramebufferRenderbuffer = (PFNGLFRAMEBUFFERRENDERBUFFERPROC)OglGetProc("glFramebufferRenderbuffer");
		OglGetFramebufferAttachmentParameteriv = (PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC)OglGetProc("glGetFramebufferAttachmentParameteriv");
		OglGenerateMipmap = (PFNGLGENERATEMIPMAPPROC)OglGetProc("glGenerateMipmap");
		OglBlitFramebuffer = (PFNGLBLITFRAMEBUFFERPROC)OglGetProc("glBlitFramebuffer");
		OglRenderbufferStorageMultisample = (PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC)OglGetProc("glRenderbufferStorageMultisample");
		OglFramebufferTextureLayer = (PFNGLFRAMEBUFFERTEXTURELAYERPROC)OglGetProc("glFramebufferTextureLayer");
		OglMapBufferRange = (PFNGLMAPBUFFERRANGEPROC)OglGetProc("glMapBufferRange");
		OglFlushMappedBufferRange = (PFNGLFLUSHMAPPEDBUFFERRANGEPROC)OglGetProc("glFlushMappedBufferRange");
		OglBindVertexArray = (PFNGLBINDVERTEXARRAYPROC)OglGetProc("glBindVertexArray");
		OglDeleteVertexArrays = (PFNGLDELETEVERTEXARRAYSPROC)OglGetProc("glDeleteVertexArrays");
		OglGenVertexArrays = (PFNGLGENVERTEXARRAYSPROC)OglGetProc("glGenVertexArrays");
		OglIsVertexArray = (PFNGLISVERTEXARRAYPROC)OglGetProc("glIsVertexArray");
		OglGetUniformIndices = (PFNGLGETUNIFORMINDICESPROC)OglGetProc("glGetUniformIndices");
		OglGetActiveUniformsiv = (PFNGLGETACTIVEUNIFORMSIVPROC)OglGetProc("glGetActiveUniformsiv");
		OglGetActiveUniformName = (PFNGLGETACTIVEUNIFORMNAMEPROC)OglGetProc("glGetActiveUniformName");
		OglGetUniformBlockIndex = (PFNGLGETUNIFORMBLOCKINDEXPROC)OglGetProc("glGetUniformBlockIndex");
		OglGetActiveUniformBlockiv = (PFNGLGETACTIVEUNIFORMBLOCKIVPROC)OglGetProc("glGetActiveUniformBlockiv");
		OglGetActiveUniformBlockName = (PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC)OglGetProc("glGetActiveUniformBlockName");
		OglUniformBlockBinding = (PFNGLUNIFORMBLOCKBINDINGPROC)OglGetProc("glUniformBlockBinding");
		OglCopyBufferSubData = (PFNGLCOPYBUFFERSUBDATAPROC)OglGetProc("glCopyBufferSubData");
		OglDrawElementsBaseVertex = (PFNGLDRAWELEMENTSBASEVERTEXPROC)OglGetProc("glDrawElementsBaseVertex");
		OglDrawRangeElementsBaseVertex = (PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC)OglGetProc("glDrawRangeElementsBaseVertex");
		OglDrawElementsInstancedBaseVertex = (PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC)OglGetProc("glDrawElementsInstancedBaseVertex");
		OglMultiDrawElementsBaseVertex = (PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC)OglGetProc("glMultiDrawElementsBaseVertex");
		OglProvokingVertex = (PFNGLPROVOKINGVERTEXPROC)OglGetProc("glProvokingVertex");
		OglFenceSync = (PFNGLFENCESYNCPROC)OglGetProc("glFenceSync");
		OglIsSync = (PFNGLISSYNCPROC)OglGetProc("glIsSync");
		OglDeleteSync = (PFNGLDELETESYNCPROC)OglGetProc("glDeleteSync");
		OglClientWaitSync = (PFNGLCLIENTWAITSYNCPROC)OglGetProc("glClientWaitSync");
		OglWaitSync = (PFNGLWAITSYNCPROC)OglGetProc("glWaitSync");
		OglGetInteger64v = (PFNGLGETINTEGER64VPROC)OglGetProc("glGetInteger64v");
		OglGetSynciv = (PFNGLGETSYNCIVPROC)OglGetProc("glGetSynciv");
		OglTexImage2DMultisample = (PFNGLTEXIMAGE2DMULTISAMPLEPROC)OglGetProc("glTexImage2DMultisample");
		OglTexImage3DMultisample = (PFNGLTEXIMAGE3DMULTISAMPLEPROC)OglGetProc("glTexImage3DMultisample");
		OglGetMultisamplefv = (PFNGLGETMULTISAMPLEFVPROC)OglGetProc("glGetMultisamplefv");
		OglSampleMaski = (PFNGLSAMPLEMASKIPROC)OglGetProc("glSampleMaski");
		OglBlendEquationiARB = (PFNGLBLENDEQUATIONIARBPROC)OglGetProc("glBlendEquationiARB");
		OglBlendEquationSeparateiARB = (PFNGLBLENDEQUATIONSEPARATEIARBPROC)OglGetProc("glBlendEquationSeparateiARB");
		OglBlendFunciARB = (PFNGLBLENDFUNCIARBPROC)OglGetProc("glBlendFunciARB");
		OglBlendFuncSeparateiARB = (PFNGLBLENDFUNCSEPARATEIARBPROC)OglGetProc("glBlendFuncSeparateiARB");
		OglMinSampleShadingARB = (PFNGLMINSAMPLESHADINGARBPROC)OglGetProc("glMinSampleShadingARB");
		OglNamedStringARB = (PFNGLNAMEDSTRINGARBPROC)OglGetProc("glNamedStringARB");
		OglDeleteNamedStringARB = (PFNGLDELETENAMEDSTRINGARBPROC)OglGetProc("glDeleteNamedStringARB");
		OglCompileShaderIncludeARB = (PFNGLCOMPILESHADERINCLUDEARBPROC)OglGetProc("glCompileShaderIncludeARB");
		OglIsNamedStringARB = (PFNGLISNAMEDSTRINGARBPROC)OglGetProc("glIsNamedStringARB");
		OglGetNamedStringARB = (PFNGLGETNAMEDSTRINGARBPROC)OglGetProc("glGetNamedStringARB");
		OglGetNamedStringivARB = (PFNGLGETNAMEDSTRINGIVARBPROC)OglGetProc("glGetNamedStringivARB");
		OglBindFragDataLocationIndexed = (PFNGLBINDFRAGDATALOCATIONINDEXEDPROC)OglGetProc("glBindFragDataLocationIndexed");
		OglGetFragDataIndex = (PFNGLGETFRAGDATAINDEXPROC)OglGetProc("glGetFragDataIndex");
		OglGenSamplers = (PFNGLGENSAMPLERSPROC)OglGetProc("glGenSamplers");
		OglDeleteSamplers = (PFNGLDELETESAMPLERSPROC)OglGetProc("glDeleteSamplers");
		OglIsSampler = (PFNGLISSAMPLERPROC)OglGetProc("glIsSampler");
		OglBindSampler = (PFNGLBINDSAMPLERPROC)OglGetProc("glBindSampler");
		OglSamplerParameteri = (PFNGLSAMPLERPARAMETERIPROC)OglGetProc("glSamplerParameteri");
		OglSamplerParameteriv = (PFNGLSAMPLERPARAMETERIVPROC)OglGetProc("glSamplerParameteriv");
		OglSamplerParameterf = (PFNGLSAMPLERPARAMETERFPROC)OglGetProc("glSamplerParameterf");
		OglSamplerParameterfv = (PFNGLSAMPLERPARAMETERFVPROC)OglGetProc("glSamplerParameterfv");
		OglSamplerParameterIiv = (PFNGLSAMPLERPARAMETERIIVPROC)OglGetProc("glSamplerParameterIiv");
		OglSamplerParameterIuiv = (PFNGLSAMPLERPARAMETERIUIVPROC)OglGetProc("glSamplerParameterIuiv");
		OglGetSamplerParameteriv = (PFNGLGETSAMPLERPARAMETERIVPROC)OglGetProc("glGetSamplerParameteriv");
		OglGetSamplerParameterIiv = (PFNGLGETSAMPLERPARAMETERIIVPROC)OglGetProc("glGetSamplerParameterIiv");
		OglGetSamplerParameterfv = (PFNGLGETSAMPLERPARAMETERFVPROC)OglGetProc("glGetSamplerParameterfv");
		OglGetSamplerParameterIuiv = (PFNGLGETSAMPLERPARAMETERIUIVPROC)OglGetProc("glGetSamplerParameterIuiv");
		OglQueryCounter = (PFNGLQUERYCOUNTERPROC)OglGetProc("glQueryCounter");
		OglGetQueryObjecti64v = (PFNGLGETQUERYOBJECTI64VPROC)OglGetProc("glGetQueryObjecti64v");
		OglGetQueryObjectui64v = (PFNGLGETQUERYOBJECTUI64VPROC)OglGetProc("glGetQueryObjectui64v");
		OglVertexP2ui = (PFNGLVERTEXP2UIPROC)OglGetProc("glVertexP2ui");
		OglVertexP2uiv = (PFNGLVERTEXP2UIVPROC)OglGetProc("glVertexP2uiv");
		OglVertexP3ui = (PFNGLVERTEXP3UIPROC)OglGetProc("glVertexP3ui");
		OglVertexP3uiv = (PFNGLVERTEXP3UIVPROC)OglGetProc("glVertexP3uiv");
		OglVertexP4ui = (PFNGLVERTEXP4UIPROC)OglGetProc("glVertexP4ui");
		OglVertexP4uiv = (PFNGLVERTEXP4UIVPROC)OglGetProc("glVertexP4uiv");
		OglTexCoordP1ui = (PFNGLTEXCOORDP1UIPROC)OglGetProc("glTexCoordP1ui");
		OglTexCoordP1uiv = (PFNGLTEXCOORDP1UIVPROC)OglGetProc("glTexCoordP1uiv");
		OglTexCoordP2ui = (PFNGLTEXCOORDP2UIPROC)OglGetProc("glTexCoordP2ui");
		OglTexCoordP2uiv = (PFNGLTEXCOORDP2UIVPROC)OglGetProc("glTexCoordP2uiv");
		OglTexCoordP3ui = (PFNGLTEXCOORDP3UIPROC)OglGetProc("glTexCoordP3ui");
		OglTexCoordP3uiv = (PFNGLTEXCOORDP3UIVPROC)OglGetProc("glTexCoordP3uiv");
		OglTexCoordP4ui = (PFNGLTEXCOORDP4UIPROC)OglGetProc("glTexCoordP4ui");
		OglTexCoordP4uiv = (PFNGLTEXCOORDP4UIVPROC)OglGetProc("glTexCoordP4uiv");
		OglMultiTexCoordP1ui = (PFNGLMULTITEXCOORDP1UIPROC)OglGetProc("glMultiTexCoordP1ui");
		OglMultiTexCoordP1uiv = (PFNGLMULTITEXCOORDP1UIVPROC)OglGetProc("glMultiTexCoordP1uiv");
		OglMultiTexCoordP2ui = (PFNGLMULTITEXCOORDP2UIPROC)OglGetProc("glMultiTexCoordP2ui");
		OglMultiTexCoordP2uiv = (PFNGLMULTITEXCOORDP2UIVPROC)OglGetProc("glMultiTexCoordP2uiv");
		OglMultiTexCoordP3ui = (PFNGLMULTITEXCOORDP3UIPROC)OglGetProc("glMultiTexCoordP3ui");
		OglMultiTexCoordP3uiv = (PFNGLMULTITEXCOORDP3UIVPROC)OglGetProc("glMultiTexCoordP3uiv");
		OglMultiTexCoordP4ui = (PFNGLMULTITEXCOORDP4UIPROC)OglGetProc("glMultiTexCoordP4ui");
		OglMultiTexCoordP4uiv = (PFNGLMULTITEXCOORDP4UIVPROC)OglGetProc("glMultiTexCoordP4uiv");
		OglNormalP3ui = (PFNGLNORMALP3UIPROC)OglGetProc("glNormalP3ui");
		OglNormalP3uiv = (PFNGLNORMALP3UIVPROC)OglGetProc("glNormalP3uiv");
		OglColorP3ui = (PFNGLCOLORP3UIPROC)OglGetProc("glColorP3ui");
		OglColorP3uiv = (PFNGLCOLORP3UIVPROC)OglGetProc("glColorP3uiv");
		OglColorP4ui = (PFNGLCOLORP4UIPROC)OglGetProc("glColorP4ui");
		OglColorP4uiv = (PFNGLCOLORP4UIVPROC)OglGetProc("glColorP4uiv");
		OglSecondaryColorP3ui = (PFNGLSECONDARYCOLORP3UIPROC)OglGetProc("glSecondaryColorP3ui");
		OglSecondaryColorP3uiv = (PFNGLSECONDARYCOLORP3UIVPROC)OglGetProc("glSecondaryColorP3uiv");
		OglVertexAttribP1ui = (PFNGLVERTEXATTRIBP1UIPROC)OglGetProc("glVertexAttribP1ui");
		OglVertexAttribP1uiv = (PFNGLVERTEXATTRIBP1UIVPROC)OglGetProc("glVertexAttribP1uiv");
		OglVertexAttribP2ui = (PFNGLVERTEXATTRIBP2UIPROC)OglGetProc("glVertexAttribP2ui");
		OglVertexAttribP2uiv = (PFNGLVERTEXATTRIBP2UIVPROC)OglGetProc("glVertexAttribP2uiv");
		OglVertexAttribP3ui = (PFNGLVERTEXATTRIBP3UIPROC)OglGetProc("glVertexAttribP3ui");
		OglVertexAttribP3uiv = (PFNGLVERTEXATTRIBP3UIVPROC)OglGetProc("glVertexAttribP3uiv");
		OglVertexAttribP4ui = (PFNGLVERTEXATTRIBP4UIPROC)OglGetProc("glVertexAttribP4ui");
		OglVertexAttribP4uiv = (PFNGLVERTEXATTRIBP4UIVPROC)OglGetProc("glVertexAttribP4uiv");
		OglDrawArraysIndirect = (PFNGLDRAWARRAYSINDIRECTPROC)OglGetProc("glDrawArraysIndirect");
		OglDrawElementsIndirect = (PFNGLDRAWELEMENTSINDIRECTPROC)OglGetProc("glDrawElementsIndirect");
		OglUniform1d = (PFNGLUNIFORM1DPROC)OglGetProc("glUniform1d");
		OglUniform2d = (PFNGLUNIFORM2DPROC)OglGetProc("glUniform2d");
		OglUniform3d = (PFNGLUNIFORM3DPROC)OglGetProc("glUniform3d");
		OglUniform4d = (PFNGLUNIFORM4DPROC)OglGetProc("glUniform4d");
		OglUniform1dv = (PFNGLUNIFORM1DVPROC)OglGetProc("glUniform1dv");
		OglUniform2dv = (PFNGLUNIFORM2DVPROC)OglGetProc("glUniform2dv");
		OglUniform3dv = (PFNGLUNIFORM3DVPROC)OglGetProc("glUniform3dv");
		OglUniform4dv = (PFNGLUNIFORM4DVPROC)OglGetProc("glUniform4dv");
		OglUniformMatrix2dv = (PFNGLUNIFORMMATRIX2DVPROC)OglGetProc("glUniformMatrix2dv");
		OglUniformMatrix3dv = (PFNGLUNIFORMMATRIX3DVPROC)OglGetProc("glUniformMatrix3dv");
		OglUniformMatrix4dv = (PFNGLUNIFORMMATRIX4DVPROC)OglGetProc("glUniformMatrix4dv");
		OglUniformMatrix2x3dv = (PFNGLUNIFORMMATRIX2X3DVPROC)OglGetProc("glUniformMatrix2x3dv");
		OglUniformMatrix2x4dv = (PFNGLUNIFORMMATRIX2X4DVPROC)OglGetProc("glUniformMatrix2x4dv");
		OglUniformMatrix3x2dv = (PFNGLUNIFORMMATRIX3X2DVPROC)OglGetProc("glUniformMatrix3x2dv");
		OglUniformMatrix3x4dv = (PFNGLUNIFORMMATRIX3X4DVPROC)OglGetProc("glUniformMatrix3x4dv");
		OglUniformMatrix4x2dv = (PFNGLUNIFORMMATRIX4X2DVPROC)OglGetProc("glUniformMatrix4x2dv");
		OglUniformMatrix4x3dv = (PFNGLUNIFORMMATRIX4X3DVPROC)OglGetProc("glUniformMatrix4x3dv");
		OglGetUniformdv = (PFNGLGETUNIFORMDVPROC)OglGetProc("glGetUniformdv");
		OglGetSubroutineUniformLocation = (PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC)OglGetProc("glGetSubroutineUniformLocation");
		OglGetSubroutineIndex = (PFNGLGETSUBROUTINEINDEXPROC)OglGetProc("glGetSubroutineIndex");
		OglGetActiveSubroutineUniformiv = (PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC)OglGetProc("glGetActiveSubroutineUniformiv");
		OglGetActiveSubroutineUniformName = (PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC)OglGetProc("glGetActiveSubroutineUniformName");
		OglGetActiveSubroutineName = (PFNGLGETACTIVESUBROUTINENAMEPROC)OglGetProc("glGetActiveSubroutineName");
		OglUniformSubroutinesuiv = (PFNGLUNIFORMSUBROUTINESUIVPROC)OglGetProc("glUniformSubroutinesuiv");
		OglGetUniformSubroutineuiv = (PFNGLGETUNIFORMSUBROUTINEUIVPROC)OglGetProc("glGetUniformSubroutineuiv");
		OglGetProgramStageiv = (PFNGLGETPROGRAMSTAGEIVPROC)OglGetProc("glGetProgramStageiv");
		OglPatchParameteri = (PFNGLPATCHPARAMETERIPROC)OglGetProc("glPatchParameteri");
		OglPatchParameterfv = (PFNGLPATCHPARAMETERFVPROC)OglGetProc("glPatchParameterfv");
		OglBindTransformFeedback = (PFNGLBINDTRANSFORMFEEDBACKPROC)OglGetProc("glBindTransformFeedback");
		OglDeleteTransformFeedbacks = (PFNGLDELETETRANSFORMFEEDBACKSPROC)OglGetProc("glDeleteTransformFeedbacks");
		OglGenTransformFeedbacks = (PFNGLGENTRANSFORMFEEDBACKSPROC)OglGetProc("glGenTransformFeedbacks");
		OglIsTransformFeedback = (PFNGLISTRANSFORMFEEDBACKPROC)OglGetProc("glIsTransformFeedback");
		OglPauseTransformFeedback = (PFNGLPAUSETRANSFORMFEEDBACKPROC)OglGetProc("glPauseTransformFeedback");
		OglResumeTransformFeedback = (PFNGLRESUMETRANSFORMFEEDBACKPROC)OglGetProc("glResumeTransformFeedback");
		OglDrawTransformFeedback = (PFNGLDRAWTRANSFORMFEEDBACKPROC)OglGetProc("glDrawTransformFeedback");
		OglDrawTransformFeedbackStream = (PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC)OglGetProc("glDrawTransformFeedbackStream");
		OglBeginQueryIndexed = (PFNGLBEGINQUERYINDEXEDPROC)OglGetProc("glBeginQueryIndexed");
		OglEndQueryIndexed = (PFNGLENDQUERYINDEXEDPROC)OglGetProc("glEndQueryIndexed");
		OglGetQueryIndexediv = (PFNGLGETQUERYINDEXEDIVPROC)OglGetProc("glGetQueryIndexediv");
		OglReleaseShaderCompiler = (PFNGLRELEASESHADERCOMPILERPROC)OglGetProc("glReleaseShaderCompiler");
		OglShaderBinary = (PFNGLSHADERBINARYPROC)OglGetProc("glShaderBinary");
		OglGetShaderPrecisionFormat = (PFNGLGETSHADERPRECISIONFORMATPROC)OglGetProc("glGetShaderPrecisionFormat");
		OglDepthRangef = (PFNGLDEPTHRANGEFPROC)OglGetProc("glDepthRangef");
		OglClearDepthf = (PFNGLCLEARDEPTHFPROC)OglGetProc("glClearDepthf");
		OglGetProgramBinary = (PFNGLGETPROGRAMBINARYPROC)OglGetProc("glGetProgramBinary");
		OglProgramBinary = (PFNGLPROGRAMBINARYPROC)OglGetProc("glProgramBinary");
		OglProgramParameteri = (PFNGLPROGRAMPARAMETERIPROC)OglGetProc("glProgramParameteri");
		OglUseProgramStages = (PFNGLUSEPROGRAMSTAGESPROC)OglGetProc("glUseProgramStages");
		OglActiveShaderProgram = (PFNGLACTIVESHADERPROGRAMPROC)OglGetProc("glActiveShaderProgram");
		OglCreateShaderProgramv = (PFNGLCREATESHADERPROGRAMVPROC)OglGetProc("glCreateShaderProgramv");
		OglBindProgramPipeline = (PFNGLBINDPROGRAMPIPELINEPROC)OglGetProc("glBindProgramPipeline");
		OglDeleteProgramPipelines = (PFNGLDELETEPROGRAMPIPELINESPROC)OglGetProc("glDeleteProgramPipelines");
		OglGenProgramPipelines = (PFNGLGENPROGRAMPIPELINESPROC)OglGetProc("glGenProgramPipelines");
		OglIsProgramPipeline = (PFNGLISPROGRAMPIPELINEPROC)OglGetProc("glIsProgramPipeline");
		OglGetProgramPipelineiv = (PFNGLGETPROGRAMPIPELINEIVPROC)OglGetProc("glGetProgramPipelineiv");
		OglProgramUniform1i = (PFNGLPROGRAMUNIFORM1IPROC)OglGetProc("glProgramUniform1i");
		OglProgramUniform1iv = (PFNGLPROGRAMUNIFORM1IVPROC)OglGetProc("glProgramUniform1iv");
		OglProgramUniform1f = (PFNGLPROGRAMUNIFORM1FPROC)OglGetProc("glProgramUniform1f");
		OglProgramUniform1fv = (PFNGLPROGRAMUNIFORM1FVPROC)OglGetProc("glProgramUniform1fv");
		OglProgramUniform1d = (PFNGLPROGRAMUNIFORM1DPROC)OglGetProc("glProgramUniform1d");
		OglProgramUniform1dv = (PFNGLPROGRAMUNIFORM1DVPROC)OglGetProc("glProgramUniform1dv");
		OglProgramUniform1ui = (PFNGLPROGRAMUNIFORM1UIPROC)OglGetProc("glProgramUniform1ui");
		OglProgramUniform1uiv = (PFNGLPROGRAMUNIFORM1UIVPROC)OglGetProc("glProgramUniform1uiv");
		OglProgramUniform2i = (PFNGLPROGRAMUNIFORM2IPROC)OglGetProc("glProgramUniform2i");
		OglProgramUniform2iv = (PFNGLPROGRAMUNIFORM2IVPROC)OglGetProc("glProgramUniform2iv");
		OglProgramUniform2f = (PFNGLPROGRAMUNIFORM2FPROC)OglGetProc("glProgramUniform2f");
		OglProgramUniform2fv = (PFNGLPROGRAMUNIFORM2FVPROC)OglGetProc("glProgramUniform2fv");
		OglProgramUniform2d = (PFNGLPROGRAMUNIFORM2DPROC)OglGetProc("glProgramUniform2d");
		OglProgramUniform2dv = (PFNGLPROGRAMUNIFORM2DVPROC)OglGetProc("glProgramUniform2dv");
		OglProgramUniform2ui = (PFNGLPROGRAMUNIFORM2UIPROC)OglGetProc("glProgramUniform2ui");
		OglProgramUniform2uiv = (PFNGLPROGRAMUNIFORM2UIVPROC)OglGetProc("glProgramUniform2uiv");
		OglProgramUniform3i = (PFNGLPROGRAMUNIFORM3IPROC)OglGetProc("glProgramUniform3i");
		OglProgramUniform3iv = (PFNGLPROGRAMUNIFORM3IVPROC)OglGetProc("glProgramUniform3iv");
		OglProgramUniform3f = (PFNGLPROGRAMUNIFORM3FPROC)OglGetProc("glProgramUniform3f");
		OglProgramUniform3fv = (PFNGLPROGRAMUNIFORM3FVPROC)OglGetProc("glProgramUniform3fv");
		OglProgramUniform3d = (PFNGLPROGRAMUNIFORM3DPROC)OglGetProc("glProgramUniform3d");
		OglProgramUniform3dv = (PFNGLPROGRAMUNIFORM3DVPROC)OglGetProc("glProgramUniform3dv");
		OglProgramUniform3ui = (PFNGLPROGRAMUNIFORM3UIPROC)OglGetProc("glProgramUniform3ui");
		OglProgramUniform3uiv = (PFNGLPROGRAMUNIFORM3UIVPROC)OglGetProc("glProgramUniform3uiv");
		OglProgramUniform4i = (PFNGLPROGRAMUNIFORM4IPROC)OglGetProc("glProgramUniform4i");
		OglProgramUniform4iv = (PFNGLPROGRAMUNIFORM4IVPROC)OglGetProc("glProgramUniform4iv");
		OglProgramUniform4f = (PFNGLPROGRAMUNIFORM4FPROC)OglGetProc("glProgramUniform4f");
		OglProgramUniform4fv = (PFNGLPROGRAMUNIFORM4FVPROC)OglGetProc("glProgramUniform4fv");
		OglProgramUniform4d = (PFNGLPROGRAMUNIFORM4DPROC)OglGetProc("glProgramUniform4d");
		OglProgramUniform4dv = (PFNGLPROGRAMUNIFORM4DVPROC)OglGetProc("glProgramUniform4dv");
		OglProgramUniform4ui = (PFNGLPROGRAMUNIFORM4UIPROC)OglGetProc("glProgramUniform4ui");
		OglProgramUniform4uiv = (PFNGLPROGRAMUNIFORM4UIVPROC)OglGetProc("glProgramUniform4uiv");
		OglProgramUniformMatrix2fv = (PFNGLPROGRAMUNIFORMMATRIX2FVPROC)OglGetProc("glProgramUniformMatrix2fv");
		OglProgramUniformMatrix3fv = (PFNGLPROGRAMUNIFORMMATRIX3FVPROC)OglGetProc("glProgramUniformMatrix3fv");
		OglProgramUniformMatrix4fv = (PFNGLPROGRAMUNIFORMMATRIX4FVPROC)OglGetProc("glProgramUniformMatrix4fv");
		OglProgramUniformMatrix2dv = (PFNGLPROGRAMUNIFORMMATRIX2DVPROC)OglGetProc("glProgramUniformMatrix2dv");
		OglProgramUniformMatrix3dv = (PFNGLPROGRAMUNIFORMMATRIX3DVPROC)OglGetProc("glProgramUniformMatrix3dv");
		OglProgramUniformMatrix4dv = (PFNGLPROGRAMUNIFORMMATRIX4DVPROC)OglGetProc("glProgramUniformMatrix4dv");
		OglProgramUniformMatrix2x3fv = (PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC)OglGetProc("glProgramUniformMatrix2x3fv");
		OglProgramUniformMatrix3x2fv = (PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC)OglGetProc("glProgramUniformMatrix3x2fv");
		OglProgramUniformMatrix2x4fv = (PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC)OglGetProc("glProgramUniformMatrix2x4fv");
		OglProgramUniformMatrix4x2fv = (PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC)OglGetProc("glProgramUniformMatrix4x2fv");
		OglProgramUniformMatrix3x4fv = (PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC)OglGetProc("glProgramUniformMatrix3x4fv");
		OglProgramUniformMatrix4x3fv = (PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC)OglGetProc("glProgramUniformMatrix4x3fv");
		OglProgramUniformMatrix2x3dv = (PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC)OglGetProc("glProgramUniformMatrix2x3dv");
		OglProgramUniformMatrix3x2dv = (PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC)OglGetProc("glProgramUniformMatrix3x2dv");
		OglProgramUniformMatrix2x4dv = (PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC)OglGetProc("glProgramUniformMatrix2x4dv");
		OglProgramUniformMatrix4x2dv = (PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC)OglGetProc("glProgramUniformMatrix4x2dv");
		OglProgramUniformMatrix3x4dv = (PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC)OglGetProc("glProgramUniformMatrix3x4dv");
		OglProgramUniformMatrix4x3dv = (PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC)OglGetProc("glProgramUniformMatrix4x3dv");
		OglValidateProgramPipeline = (PFNGLVALIDATEPROGRAMPIPELINEPROC)OglGetProc("glValidateProgramPipeline");
		OglGetProgramPipelineInfoLog = (PFNGLGETPROGRAMPIPELINEINFOLOGPROC)OglGetProc("glGetProgramPipelineInfoLog");
		OglVertexAttribL1d = (PFNGLVERTEXATTRIBL1DPROC)OglGetProc("glVertexAttribL1d");
		OglVertexAttribL2d = (PFNGLVERTEXATTRIBL2DPROC)OglGetProc("glVertexAttribL2d");
		OglVertexAttribL3d = (PFNGLVERTEXATTRIBL3DPROC)OglGetProc("glVertexAttribL3d");
		OglVertexAttribL4d = (PFNGLVERTEXATTRIBL4DPROC)OglGetProc("glVertexAttribL4d");
		OglVertexAttribL1dv = (PFNGLVERTEXATTRIBL1DVPROC)OglGetProc("glVertexAttribL1dv");
		OglVertexAttribL2dv = (PFNGLVERTEXATTRIBL2DVPROC)OglGetProc("glVertexAttribL2dv");
		OglVertexAttribL3dv = (PFNGLVERTEXATTRIBL3DVPROC)OglGetProc("glVertexAttribL3dv");
		OglVertexAttribL4dv = (PFNGLVERTEXATTRIBL4DVPROC)OglGetProc("glVertexAttribL4dv");
		OglVertexAttribLPointer = (PFNGLVERTEXATTRIBLPOINTERPROC)OglGetProc("glVertexAttribLPointer");
		OglGetVertexAttribLdv = (PFNGLGETVERTEXATTRIBLDVPROC)OglGetProc("glGetVertexAttribLdv");
		OglViewportArrayv = (PFNGLVIEWPORTARRAYVPROC)OglGetProc("glViewportArrayv");
		OglViewportIndexedf = (PFNGLVIEWPORTINDEXEDFPROC)OglGetProc("glViewportIndexedf");
		OglViewportIndexedfv = (PFNGLVIEWPORTINDEXEDFVPROC)OglGetProc("glViewportIndexedfv");
		OglScissorArrayv = (PFNGLSCISSORARRAYVPROC)OglGetProc("glScissorArrayv");
		OglScissorIndexed = (PFNGLSCISSORINDEXEDPROC)OglGetProc("glScissorIndexed");
		OglScissorIndexedv = (PFNGLSCISSORINDEXEDVPROC)OglGetProc("glScissorIndexedv");
		OglDepthRangeArrayv = (PFNGLDEPTHRANGEARRAYVPROC)OglGetProc("glDepthRangeArrayv");
		OglDepthRangeIndexed = (PFNGLDEPTHRANGEINDEXEDPROC)OglGetProc("glDepthRangeIndexed");
		OglGetFloati_v = (PFNGLGETFLOATI_VPROC)OglGetProc("glGetFloati_v");
		OglGetDoublei_v = (PFNGLGETDOUBLEI_VPROC)OglGetProc("glGetDoublei_v");
		OglCreateSyncFromCLeventARB = (PFNGLCREATESYNCFROMCLEVENTARBPROC)OglGetProc("glCreateSyncFromCLeventARB");
		OglDebugMessageControlARB = (PFNGLDEBUGMESSAGECONTROLARBPROC)OglGetProc("glDebugMessageControlARB");
		OglDebugMessageInsertARB = (PFNGLDEBUGMESSAGEINSERTARBPROC)OglGetProc("glDebugMessageInsertARB");
		OglDebugMessageCallbackARB = (PFNGLDEBUGMESSAGECALLBACKARBPROC)OglGetProc("glDebugMessageCallbackARB");
		OglGetDebugMessageLogARB = (PFNGLGETDEBUGMESSAGELOGARBPROC)OglGetProc("glGetDebugMessageLogARB");
		OglGetGraphicsResetStatusARB = (PFNGLGETGRAPHICSRESETSTATUSARBPROC)OglGetProc("glGetGraphicsResetStatusARB");
		OglGetnTexImageARB = (PFNGLGETNTEXIMAGEARBPROC)OglGetProc("glGetnTexImageARB");
		OglReadnPixelsARB = (PFNGLREADNPIXELSARBPROC)OglGetProc("glReadnPixelsARB");
		OglGetnCompressedTexImageARB = (PFNGLGETNCOMPRESSEDTEXIMAGEARBPROC)OglGetProc("glGetnCompressedTexImageARB");
		OglGetnUniformfvARB = (PFNGLGETNUNIFORMFVARBPROC)OglGetProc("glGetnUniformfvARB");
		OglGetnUniformivARB = (PFNGLGETNUNIFORMIVARBPROC)OglGetProc("glGetnUniformivARB");
		OglGetnUniformuivARB = (PFNGLGETNUNIFORMUIVARBPROC)OglGetProc("glGetnUniformuivARB");
		OglGetnUniformdvARB = (PFNGLGETNUNIFORMDVARBPROC)OglGetProc("glGetnUniformdvARB");
		OglDrawArraysInstancedBaseInstance = (PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC)OglGetProc("glDrawArraysInstancedBaseInstance");
		OglDrawElementsInstancedBaseInstance = (PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC)OglGetProc("glDrawElementsInstancedBaseInstance");
		OglDrawElementsInstancedBaseVertexBaseInstance = (PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC)OglGetProc("glDrawElementsInstancedBaseVertexBaseInstance");
		OglDrawTransformFeedbackInstanced = (PFNGLDRAWTRANSFORMFEEDBACKINSTANCEDPROC)OglGetProc("glDrawTransformFeedbackInstanced");
		OglDrawTransformFeedbackStreamInstanced = (PFNGLDRAWTRANSFORMFEEDBACKSTREAMINSTANCEDPROC)OglGetProc("glDrawTransformFeedbackStreamInstanced");
		OglGetInternalformativ = (PFNGLGETINTERNALFORMATIVPROC)OglGetProc("glGetInternalformativ");
		OglGetActiveAtomicCounterBufferiv = (PFNGLGETACTIVEATOMICCOUNTERBUFFERIVPROC)OglGetProc("glGetActiveAtomicCounterBufferiv");
		OglBindImageTexture = (PFNGLBINDIMAGETEXTUREPROC)OglGetProc("glBindImageTexture");
		OglMemoryBarrier = (PFNGLMEMORYBARRIERPROC)OglGetProc("glMemoryBarrier");
		OglTexStorage1D = (PFNGLTEXSTORAGE1DPROC)OglGetProc("glTexStorage1D");
		OglTexStorage2D = (PFNGLTEXSTORAGE2DPROC)OglGetProc("glTexStorage2D");
		OglTexStorage3D = (PFNGLTEXSTORAGE3DPROC)OglGetProc("glTexStorage3D");
		OglTextureStorage1DEXT = (PFNGLTEXTURESTORAGE1DEXTPROC)OglGetProc("glTextureStorage1DEXT");
		OglTextureStorage2DEXT = (PFNGLTEXTURESTORAGE2DEXTPROC)OglGetProc("glTextureStorage2DEXT");
		OglTextureStorage3DEXT = (PFNGLTEXTURESTORAGE3DEXTPROC)OglGetProc("glTextureStorage3DEXT");
		OglDebugMessageControl = (PFNGLDEBUGMESSAGECONTROLPROC)OglGetProc("glDebugMessageControl");
		OglDebugMessageInsert = (PFNGLDEBUGMESSAGEINSERTPROC)OglGetProc("glDebugMessageInsert");
		OglDebugMessageCallback = (PFNGLDEBUGMESSAGECALLBACKPROC)OglGetProc("glDebugMessageCallback");
		OglGetDebugMessageLog = (PFNGLGETDEBUGMESSAGELOGPROC)OglGetProc("glGetDebugMessageLog");
		OglPushDebugGroup = (PFNGLPUSHDEBUGGROUPPROC)OglGetProc("glPushDebugGroup");
		OglPopDebugGroup = (PFNGLPOPDEBUGGROUPPROC)OglGetProc("glPopDebugGroup");
		OglObjectLabel = (PFNGLOBJECTLABELPROC)OglGetProc("glObjectLabel");
		OglGetObjectLabel = (PFNGLGETOBJECTLABELPROC)OglGetProc("glGetObjectLabel");
		OglObjectPtrLabel = (PFNGLOBJECTPTRLABELPROC)OglGetProc("glObjectPtrLabel");
		OglGetObjectPtrLabel = (PFNGLGETOBJECTPTRLABELPROC)OglGetProc("glGetObjectPtrLabel");
		OglClearBufferData = (PFNGLCLEARBUFFERDATAPROC)OglGetProc("glClearBufferData");
		OglClearBufferSubData = (PFNGLCLEARBUFFERSUBDATAPROC)OglGetProc("glClearBufferSubData");
		OglClearNamedBufferDataEXT = (PFNGLCLEARNAMEDBUFFERDATAEXTPROC)OglGetProc("glClearNamedBufferDataEXT");
		OglClearNamedBufferSubDataEXT = (PFNGLCLEARNAMEDBUFFERSUBDATAEXTPROC)OglGetProc("glClearNamedBufferSubDataEXT");
		OglDispatchCompute = (PFNGLDISPATCHCOMPUTEPROC)OglGetProc("glDispatchCompute");
		OglDispatchComputeIndirect = (PFNGLDISPATCHCOMPUTEINDIRECTPROC)OglGetProc("glDispatchComputeIndirect");
		OglCopyImageSubData = (PFNGLCOPYIMAGESUBDATAPROC)OglGetProc("glCopyImageSubData");
		OglTextureView = (PFNGLTEXTUREVIEWPROC)OglGetProc("glTextureView");
		OglBindVertexBuffer = (PFNGLBINDVERTEXBUFFERPROC)OglGetProc("glBindVertexBuffer");
		OglVertexAttribFormat = (PFNGLVERTEXATTRIBFORMATPROC)OglGetProc("glVertexAttribFormat");
		OglVertexAttribIFormat = (PFNGLVERTEXATTRIBIFORMATPROC)OglGetProc("glVertexAttribIFormat");
		OglVertexAttribLFormat = (PFNGLVERTEXATTRIBLFORMATPROC)OglGetProc("glVertexAttribLFormat");
		OglVertexAttribBinding = (PFNGLVERTEXATTRIBBINDINGPROC)OglGetProc("glVertexAttribBinding");
		OglVertexBindingDivisor = (PFNGLVERTEXBINDINGDIVISORPROC)OglGetProc("glVertexBindingDivisor");
		OglVertexArrayBindVertexBufferEXT = (PFNGLVERTEXARRAYBINDVERTEXBUFFEREXTPROC)OglGetProc("glVertexArrayBindVertexBufferEXT");
		OglVertexArrayVertexAttribFormatEXT = (PFNGLVERTEXARRAYVERTEXATTRIBFORMATEXTPROC)OglGetProc("glVertexArrayVertexAttribFormatEXT");
		OglVertexArrayVertexAttribIFormatEXT = (PFNGLVERTEXARRAYVERTEXATTRIBIFORMATEXTPROC)OglGetProc("glVertexArrayVertexAttribIFormatEXT");
		OglVertexArrayVertexAttribLFormatEXT = (PFNGLVERTEXARRAYVERTEXATTRIBLFORMATEXTPROC)OglGetProc("glVertexArrayVertexAttribLFormatEXT");
		OglVertexArrayVertexAttribBindingEXT = (PFNGLVERTEXARRAYVERTEXATTRIBBINDINGEXTPROC)OglGetProc("glVertexArrayVertexAttribBindingEXT");
		OglVertexArrayVertexBindingDivisorEXT = (PFNGLVERTEXARRAYVERTEXBINDINGDIVISOREXTPROC)OglGetProc("glVertexArrayVertexBindingDivisorEXT");
		OglFramebufferParameteri = (PFNGLFRAMEBUFFERPARAMETERIPROC)OglGetProc("glFramebufferParameteri");
		OglGetFramebufferParameteriv = (PFNGLGETFRAMEBUFFERPARAMETERIVPROC)OglGetProc("glGetFramebufferParameteriv");
		OglNamedFramebufferParameteriEXT = (PFNGLNAMEDFRAMEBUFFERPARAMETERIEXTPROC)OglGetProc("glNamedFramebufferParameteriEXT");
		OglGetNamedFramebufferParameterivEXT = (PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVEXTPROC)OglGetProc("glGetNamedFramebufferParameterivEXT");
		OglGetInternalformati64v = (PFNGLGETINTERNALFORMATI64VPROC)OglGetProc("glGetInternalformati64v");
		OglInvalidateTexSubImage = (PFNGLINVALIDATETEXSUBIMAGEPROC)OglGetProc("glInvalidateTexSubImage");
		OglInvalidateTexImage = (PFNGLINVALIDATETEXIMAGEPROC)OglGetProc("glInvalidateTexImage");
		OglInvalidateBufferSubData = (PFNGLINVALIDATEBUFFERSUBDATAPROC)OglGetProc("glInvalidateBufferSubData");
		OglInvalidateBufferData = (PFNGLINVALIDATEBUFFERDATAPROC)OglGetProc("glInvalidateBufferData");
		OglInvalidateFramebuffer = (PFNGLINVALIDATEFRAMEBUFFERPROC)OglGetProc("glInvalidateFramebuffer");
		OglInvalidateSubFramebuffer = (PFNGLINVALIDATESUBFRAMEBUFFERPROC)OglGetProc("glInvalidateSubFramebuffer");
		OglMultiDrawArraysIndirect = (PFNGLMULTIDRAWARRAYSINDIRECTPROC)OglGetProc("glMultiDrawArraysIndirect");
		OglMultiDrawElementsIndirect = (PFNGLMULTIDRAWELEMENTSINDIRECTPROC)OglGetProc("glMultiDrawElementsIndirect");
		OglGetProgramInterfaceiv = (PFNGLGETPROGRAMINTERFACEIVPROC)OglGetProc("glGetProgramInterfaceiv");
		OglGetProgramResourceIndex = (PFNGLGETPROGRAMRESOURCEINDEXPROC)OglGetProc("glGetProgramResourceIndex");
		OglGetProgramResourceName = (PFNGLGETPROGRAMRESOURCENAMEPROC)OglGetProc("glGetProgramResourceName");
		OglGetProgramResourceiv = (PFNGLGETPROGRAMRESOURCEIVPROC)OglGetProc("glGetProgramResourceiv");
		OglGetProgramResourceLocation = (PFNGLGETPROGRAMRESOURCELOCATIONPROC)OglGetProc("glGetProgramResourceLocation");
		OglGetProgramResourceLocationIndex = (PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC)OglGetProc("glGetProgramResourceLocationIndex");
		OglShaderStorageBlockBinding = (PFNGLSHADERSTORAGEBLOCKBINDINGPROC)OglGetProc("glShaderStorageBlockBinding");
		OglTexBufferRange = (PFNGLTEXBUFFERRANGEPROC)OglGetProc("glTexBufferRange");
		OglTextureBufferRangeEXT = (PFNGLTEXTUREBUFFERRANGEEXTPROC)OglGetProc("glTextureBufferRangeEXT");
		OglTexStorage2DMultisample = (PFNGLTEXSTORAGE2DMULTISAMPLEPROC)OglGetProc("glTexStorage2DMultisample");
		OglTexStorage3DMultisample = (PFNGLTEXSTORAGE3DMULTISAMPLEPROC)OglGetProc("glTexStorage3DMultisample");
		OglTextureStorage2DMultisampleEXT = (PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC)OglGetProc("glTextureStorage2DMultisampleEXT");
		OglTextureStorage3DMultisampleEXT = (PFNGLTEXTURESTORAGE3DMULTISAMPLEEXTPROC)OglGetProc("glTextureStorage3DMultisampleEXT");
#endif	// NWG_OGL_ARBNWG_OGL_ARB_H
	}
}
#ifndef GL_ARB
#define GL_ARB 1
PFNGLISRENDERBUFFERPROC OglIsRenderbuffer;
PFNGLBINDRENDERBUFFERPROC OglBindRenderbuffer;
PFNGLDELETERENDERBUFFERSPROC OglDeleteRenderbuffers;
PFNGLGENRENDERBUFFERSPROC OglGenRenderbuffers;
PFNGLRENDERBUFFERSTORAGEPROC OglRenderbufferStorage;
PFNGLGETRENDERBUFFERPARAMETERIVPROC OglGetRenderbufferParameteriv;
PFNGLISFRAMEBUFFERPROC OglIsFramebuffer;
PFNGLBINDFRAMEBUFFERPROC OglBindFramebuffer;
PFNGLDELETEFRAMEBUFFERSPROC OglDeleteFramebuffers;
PFNGLGENFRAMEBUFFERSPROC OglGenFramebuffers;
PFNGLCHECKFRAMEBUFFERSTATUSPROC OglCheckFramebufferStatus;
PFNGLFRAMEBUFFERTEXTURE1DPROC OglFramebufferTexture1D;
PFNGLFRAMEBUFFERTEXTURE2DPROC OglFramebufferTexture2D;
PFNGLFRAMEBUFFERTEXTURE3DPROC OglFramebufferTexture3D;
PFNGLFRAMEBUFFERRENDERBUFFERPROC OglFramebufferRenderbuffer;
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC OglGetFramebufferAttachmentParameteriv;
PFNGLGENERATEMIPMAPPROC OglGenerateMipmap;
PFNGLBLITFRAMEBUFFERPROC OglBlitFramebuffer;
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC OglRenderbufferStorageMultisample;
PFNGLFRAMEBUFFERTEXTURELAYERPROC OglFramebufferTextureLayer;
PFNGLMAPBUFFERRANGEPROC OglMapBufferRange;
PFNGLFLUSHMAPPEDBUFFERRANGEPROC OglFlushMappedBufferRange;
PFNGLBINDVERTEXARRAYPROC OglBindVertexArray;
PFNGLDELETEVERTEXARRAYSPROC OglDeleteVertexArrays;
PFNGLGENVERTEXARRAYSPROC OglGenVertexArrays;
PFNGLISVERTEXARRAYPROC OglIsVertexArray;
PFNGLGETUNIFORMINDICESPROC OglGetUniformIndices;
PFNGLGETACTIVEUNIFORMSIVPROC OglGetActiveUniformsiv;
PFNGLGETACTIVEUNIFORMNAMEPROC OglGetActiveUniformName;
PFNGLGETUNIFORMBLOCKINDEXPROC OglGetUniformBlockIndex;
PFNGLGETACTIVEUNIFORMBLOCKIVPROC OglGetActiveUniformBlockiv;
PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC OglGetActiveUniformBlockName;
PFNGLUNIFORMBLOCKBINDINGPROC OglUniformBlockBinding;
PFNGLCOPYBUFFERSUBDATAPROC OglCopyBufferSubData;
PFNGLDRAWELEMENTSBASEVERTEXPROC OglDrawElementsBaseVertex;
PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC OglDrawRangeElementsBaseVertex;
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC OglDrawElementsInstancedBaseVertex;
PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC OglMultiDrawElementsBaseVertex;
PFNGLPROVOKINGVERTEXPROC OglProvokingVertex;
PFNGLFENCESYNCPROC OglFenceSync;
PFNGLISSYNCPROC OglIsSync;
PFNGLDELETESYNCPROC OglDeleteSync;
PFNGLCLIENTWAITSYNCPROC OglClientWaitSync;
PFNGLWAITSYNCPROC OglWaitSync;
PFNGLGETINTEGER64VPROC OglGetInteger64v;
PFNGLGETSYNCIVPROC OglGetSynciv;
PFNGLTEXIMAGE2DMULTISAMPLEPROC OglTexImage2DMultisample;
PFNGLTEXIMAGE3DMULTISAMPLEPROC OglTexImage3DMultisample;
PFNGLGETMULTISAMPLEFVPROC OglGetMultisamplefv;
PFNGLSAMPLEMASKIPROC OglSampleMaski;
PFNGLBLENDEQUATIONIARBPROC OglBlendEquationiARB;
PFNGLBLENDEQUATIONSEPARATEIARBPROC OglBlendEquationSeparateiARB;
PFNGLBLENDFUNCIARBPROC OglBlendFunciARB;
PFNGLBLENDFUNCSEPARATEIARBPROC OglBlendFuncSeparateiARB;
PFNGLMINSAMPLESHADINGARBPROC OglMinSampleShadingARB;
PFNGLNAMEDSTRINGARBPROC OglNamedStringARB;
PFNGLDELETENAMEDSTRINGARBPROC OglDeleteNamedStringARB;
PFNGLCOMPILESHADERINCLUDEARBPROC OglCompileShaderIncludeARB;
PFNGLISNAMEDSTRINGARBPROC OglIsNamedStringARB;
PFNGLGETNAMEDSTRINGARBPROC OglGetNamedStringARB;
PFNGLGETNAMEDSTRINGIVARBPROC OglGetNamedStringivARB;
PFNGLBINDFRAGDATALOCATIONINDEXEDPROC OglBindFragDataLocationIndexed;
PFNGLGETFRAGDATAINDEXPROC OglGetFragDataIndex;
PFNGLGENSAMPLERSPROC OglGenSamplers;
PFNGLDELETESAMPLERSPROC OglDeleteSamplers;
PFNGLISSAMPLERPROC OglIsSampler;
PFNGLBINDSAMPLERPROC OglBindSampler;
PFNGLSAMPLERPARAMETERIPROC OglSamplerParameteri;
PFNGLSAMPLERPARAMETERIVPROC OglSamplerParameteriv;
PFNGLSAMPLERPARAMETERFPROC OglSamplerParameterf;
PFNGLSAMPLERPARAMETERFVPROC OglSamplerParameterfv;
PFNGLSAMPLERPARAMETERIIVPROC OglSamplerParameterIiv;
PFNGLSAMPLERPARAMETERIUIVPROC OglSamplerParameterIuiv;
PFNGLGETSAMPLERPARAMETERIVPROC OglGetSamplerParameteriv;
PFNGLGETSAMPLERPARAMETERIIVPROC OglGetSamplerParameterIiv;
PFNGLGETSAMPLERPARAMETERFVPROC OglGetSamplerParameterfv;
PFNGLGETSAMPLERPARAMETERIUIVPROC OglGetSamplerParameterIuiv;
PFNGLQUERYCOUNTERPROC OglQueryCounter;
PFNGLGETQUERYOBJECTI64VPROC OglGetQueryObjecti64v;
PFNGLGETQUERYOBJECTUI64VPROC OglGetQueryObjectui64v;
PFNGLVERTEXP2UIPROC OglVertexP2ui;
PFNGLVERTEXP2UIVPROC OglVertexP2uiv;
PFNGLVERTEXP3UIPROC OglVertexP3ui;
PFNGLVERTEXP3UIVPROC OglVertexP3uiv;
PFNGLVERTEXP4UIPROC OglVertexP4ui;
PFNGLVERTEXP4UIVPROC OglVertexP4uiv;
PFNGLTEXCOORDP1UIPROC OglTexCoordP1ui;
PFNGLTEXCOORDP1UIVPROC OglTexCoordP1uiv;
PFNGLTEXCOORDP2UIPROC OglTexCoordP2ui;
PFNGLTEXCOORDP2UIVPROC OglTexCoordP2uiv;
PFNGLTEXCOORDP3UIPROC OglTexCoordP3ui;
PFNGLTEXCOORDP3UIVPROC OglTexCoordP3uiv;
PFNGLTEXCOORDP4UIPROC OglTexCoordP4ui;
PFNGLTEXCOORDP4UIVPROC OglTexCoordP4uiv;
PFNGLMULTITEXCOORDP1UIPROC OglMultiTexCoordP1ui;
PFNGLMULTITEXCOORDP1UIVPROC OglMultiTexCoordP1uiv;
PFNGLMULTITEXCOORDP2UIPROC OglMultiTexCoordP2ui;
PFNGLMULTITEXCOORDP2UIVPROC OglMultiTexCoordP2uiv;
PFNGLMULTITEXCOORDP3UIPROC OglMultiTexCoordP3ui;
PFNGLMULTITEXCOORDP3UIVPROC OglMultiTexCoordP3uiv;
PFNGLMULTITEXCOORDP4UIPROC OglMultiTexCoordP4ui;
PFNGLMULTITEXCOORDP4UIVPROC OglMultiTexCoordP4uiv;
PFNGLNORMALP3UIPROC OglNormalP3ui;
PFNGLNORMALP3UIVPROC OglNormalP3uiv;
PFNGLCOLORP3UIPROC OglColorP3ui;
PFNGLCOLORP3UIVPROC OglColorP3uiv;
PFNGLCOLORP4UIPROC OglColorP4ui;
PFNGLCOLORP4UIVPROC OglColorP4uiv;
PFNGLSECONDARYCOLORP3UIPROC OglSecondaryColorP3ui;
PFNGLSECONDARYCOLORP3UIVPROC OglSecondaryColorP3uiv;
PFNGLVERTEXATTRIBP1UIPROC OglVertexAttribP1ui;
PFNGLVERTEXATTRIBP1UIVPROC OglVertexAttribP1uiv;
PFNGLVERTEXATTRIBP2UIPROC OglVertexAttribP2ui;
PFNGLVERTEXATTRIBP2UIVPROC OglVertexAttribP2uiv;
PFNGLVERTEXATTRIBP3UIPROC OglVertexAttribP3ui;
PFNGLVERTEXATTRIBP3UIVPROC OglVertexAttribP3uiv;
PFNGLVERTEXATTRIBP4UIPROC OglVertexAttribP4ui;
PFNGLVERTEXATTRIBP4UIVPROC OglVertexAttribP4uiv;
PFNGLDRAWARRAYSINDIRECTPROC OglDrawArraysIndirect;
PFNGLDRAWELEMENTSINDIRECTPROC OglDrawElementsIndirect;
PFNGLUNIFORM1DPROC OglUniform1d;
PFNGLUNIFORM2DPROC OglUniform2d;
PFNGLUNIFORM3DPROC OglUniform3d;
PFNGLUNIFORM4DPROC OglUniform4d;
PFNGLUNIFORM1DVPROC OglUniform1dv;
PFNGLUNIFORM2DVPROC OglUniform2dv;
PFNGLUNIFORM3DVPROC OglUniform3dv;
PFNGLUNIFORM4DVPROC OglUniform4dv;
PFNGLUNIFORMMATRIX2DVPROC OglUniformMatrix2dv;
PFNGLUNIFORMMATRIX3DVPROC OglUniformMatrix3dv;
PFNGLUNIFORMMATRIX4DVPROC OglUniformMatrix4dv;
PFNGLUNIFORMMATRIX2X3DVPROC OglUniformMatrix2x3dv;
PFNGLUNIFORMMATRIX2X4DVPROC OglUniformMatrix2x4dv;
PFNGLUNIFORMMATRIX3X2DVPROC OglUniformMatrix3x2dv;
PFNGLUNIFORMMATRIX3X4DVPROC OglUniformMatrix3x4dv;
PFNGLUNIFORMMATRIX4X2DVPROC OglUniformMatrix4x2dv;
PFNGLUNIFORMMATRIX4X3DVPROC OglUniformMatrix4x3dv;
PFNGLGETUNIFORMDVPROC OglGetUniformdv;
PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC OglGetSubroutineUniformLocation;
PFNGLGETSUBROUTINEINDEXPROC OglGetSubroutineIndex;
PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC OglGetActiveSubroutineUniformiv;
PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC OglGetActiveSubroutineUniformName;
PFNGLGETACTIVESUBROUTINENAMEPROC OglGetActiveSubroutineName;
PFNGLUNIFORMSUBROUTINESUIVPROC OglUniformSubroutinesuiv;
PFNGLGETUNIFORMSUBROUTINEUIVPROC OglGetUniformSubroutineuiv;
PFNGLGETPROGRAMSTAGEIVPROC OglGetProgramStageiv;
PFNGLPATCHPARAMETERIPROC OglPatchParameteri;
PFNGLPATCHPARAMETERFVPROC OglPatchParameterfv;
PFNGLBINDTRANSFORMFEEDBACKPROC OglBindTransformFeedback;
PFNGLDELETETRANSFORMFEEDBACKSPROC OglDeleteTransformFeedbacks;
PFNGLGENTRANSFORMFEEDBACKSPROC OglGenTransformFeedbacks;
PFNGLISTRANSFORMFEEDBACKPROC OglIsTransformFeedback;
PFNGLPAUSETRANSFORMFEEDBACKPROC OglPauseTransformFeedback;
PFNGLRESUMETRANSFORMFEEDBACKPROC OglResumeTransformFeedback;
PFNGLDRAWTRANSFORMFEEDBACKPROC OglDrawTransformFeedback;
PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC OglDrawTransformFeedbackStream;
PFNGLBEGINQUERYINDEXEDPROC OglBeginQueryIndexed;
PFNGLENDQUERYINDEXEDPROC OglEndQueryIndexed;
PFNGLGETQUERYINDEXEDIVPROC OglGetQueryIndexediv;
PFNGLRELEASESHADERCOMPILERPROC OglReleaseShaderCompiler;
PFNGLSHADERBINARYPROC OglShaderBinary;
PFNGLGETSHADERPRECISIONFORMATPROC OglGetShaderPrecisionFormat;
PFNGLDEPTHRANGEFPROC OglDepthRangef;
PFNGLCLEARDEPTHFPROC OglClearDepthf;
PFNGLGETPROGRAMBINARYPROC OglGetProgramBinary;
PFNGLPROGRAMBINARYPROC OglProgramBinary;
PFNGLPROGRAMPARAMETERIPROC OglProgramParameteri;
PFNGLUSEPROGRAMSTAGESPROC OglUseProgramStages;
PFNGLACTIVESHADERPROGRAMPROC OglActiveShaderProgram;
PFNGLCREATESHADERPROGRAMVPROC OglCreateShaderProgramv;
PFNGLBINDPROGRAMPIPELINEPROC OglBindProgramPipeline;
PFNGLDELETEPROGRAMPIPELINESPROC OglDeleteProgramPipelines;
PFNGLGENPROGRAMPIPELINESPROC OglGenProgramPipelines;
PFNGLISPROGRAMPIPELINEPROC OglIsProgramPipeline;
PFNGLGETPROGRAMPIPELINEIVPROC OglGetProgramPipelineiv;
PFNGLPROGRAMUNIFORM1IPROC OglProgramUniform1i;
PFNGLPROGRAMUNIFORM1IVPROC OglProgramUniform1iv;
PFNGLPROGRAMUNIFORM1FPROC OglProgramUniform1f;
PFNGLPROGRAMUNIFORM1FVPROC OglProgramUniform1fv;
PFNGLPROGRAMUNIFORM1DPROC OglProgramUniform1d;
PFNGLPROGRAMUNIFORM1DVPROC OglProgramUniform1dv;
PFNGLPROGRAMUNIFORM1UIPROC OglProgramUniform1ui;
PFNGLPROGRAMUNIFORM1UIVPROC OglProgramUniform1uiv;
PFNGLPROGRAMUNIFORM2IPROC OglProgramUniform2i;
PFNGLPROGRAMUNIFORM2IVPROC OglProgramUniform2iv;
PFNGLPROGRAMUNIFORM2FPROC OglProgramUniform2f;
PFNGLPROGRAMUNIFORM2FVPROC OglProgramUniform2fv;
PFNGLPROGRAMUNIFORM2DPROC OglProgramUniform2d;
PFNGLPROGRAMUNIFORM2DVPROC OglProgramUniform2dv;
PFNGLPROGRAMUNIFORM2UIPROC OglProgramUniform2ui;
PFNGLPROGRAMUNIFORM2UIVPROC OglProgramUniform2uiv;
PFNGLPROGRAMUNIFORM3IPROC OglProgramUniform3i;
PFNGLPROGRAMUNIFORM3IVPROC OglProgramUniform3iv;
PFNGLPROGRAMUNIFORM3FPROC OglProgramUniform3f;
PFNGLPROGRAMUNIFORM3FVPROC OglProgramUniform3fv;
PFNGLPROGRAMUNIFORM3DPROC OglProgramUniform3d;
PFNGLPROGRAMUNIFORM3DVPROC OglProgramUniform3dv;
PFNGLPROGRAMUNIFORM3UIPROC OglProgramUniform3ui;
PFNGLPROGRAMUNIFORM3UIVPROC OglProgramUniform3uiv;
PFNGLPROGRAMUNIFORM4IPROC OglProgramUniform4i;
PFNGLPROGRAMUNIFORM4IVPROC OglProgramUniform4iv;
PFNGLPROGRAMUNIFORM4FPROC OglProgramUniform4f;
PFNGLPROGRAMUNIFORM4FVPROC OglProgramUniform4fv;
PFNGLPROGRAMUNIFORM4DPROC OglProgramUniform4d;
PFNGLPROGRAMUNIFORM4DVPROC OglProgramUniform4dv;
PFNGLPROGRAMUNIFORM4UIPROC OglProgramUniform4ui;
PFNGLPROGRAMUNIFORM4UIVPROC OglProgramUniform4uiv;
PFNGLPROGRAMUNIFORMMATRIX2FVPROC OglProgramUniformMatrix2fv;
PFNGLPROGRAMUNIFORMMATRIX3FVPROC OglProgramUniformMatrix3fv;
PFNGLPROGRAMUNIFORMMATRIX4FVPROC OglProgramUniformMatrix4fv;
PFNGLPROGRAMUNIFORMMATRIX2DVPROC OglProgramUniformMatrix2dv;
PFNGLPROGRAMUNIFORMMATRIX3DVPROC OglProgramUniformMatrix3dv;
PFNGLPROGRAMUNIFORMMATRIX4DVPROC OglProgramUniformMatrix4dv;
PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC OglProgramUniformMatrix2x3fv;
PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC OglProgramUniformMatrix3x2fv;
PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC OglProgramUniformMatrix2x4fv;
PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC OglProgramUniformMatrix4x2fv;
PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC OglProgramUniformMatrix3x4fv;
PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC OglProgramUniformMatrix4x3fv;
PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC OglProgramUniformMatrix2x3dv;
PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC OglProgramUniformMatrix3x2dv;
PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC OglProgramUniformMatrix2x4dv;
PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC OglProgramUniformMatrix4x2dv;
PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC OglProgramUniformMatrix3x4dv;
PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC OglProgramUniformMatrix4x3dv;
PFNGLVALIDATEPROGRAMPIPELINEPROC OglValidateProgramPipeline;
PFNGLGETPROGRAMPIPELINEINFOLOGPROC OglGetProgramPipelineInfoLog;
PFNGLVERTEXATTRIBL1DPROC OglVertexAttribL1d;
PFNGLVERTEXATTRIBL2DPROC OglVertexAttribL2d;
PFNGLVERTEXATTRIBL3DPROC OglVertexAttribL3d;
PFNGLVERTEXATTRIBL4DPROC OglVertexAttribL4d;
PFNGLVERTEXATTRIBL1DVPROC OglVertexAttribL1dv;
PFNGLVERTEXATTRIBL2DVPROC OglVertexAttribL2dv;
PFNGLVERTEXATTRIBL3DVPROC OglVertexAttribL3dv;
PFNGLVERTEXATTRIBL4DVPROC OglVertexAttribL4dv;
PFNGLVERTEXATTRIBLPOINTERPROC OglVertexAttribLPointer;
PFNGLGETVERTEXATTRIBLDVPROC OglGetVertexAttribLdv;
PFNGLVIEWPORTARRAYVPROC OglViewportArrayv;
PFNGLVIEWPORTINDEXEDFPROC OglViewportIndexedf;
PFNGLVIEWPORTINDEXEDFVPROC OglViewportIndexedfv;
PFNGLSCISSORARRAYVPROC OglScissorArrayv;
PFNGLSCISSORINDEXEDPROC OglScissorIndexed;
PFNGLSCISSORINDEXEDVPROC OglScissorIndexedv;
PFNGLDEPTHRANGEARRAYVPROC OglDepthRangeArrayv;
PFNGLDEPTHRANGEINDEXEDPROC OglDepthRangeIndexed;
PFNGLGETFLOATI_VPROC OglGetFloati_v;
PFNGLGETDOUBLEI_VPROC OglGetDoublei_v;
PFNGLCREATESYNCFROMCLEVENTARBPROC OglCreateSyncFromCLeventARB;
PFNGLDEBUGMESSAGECONTROLARBPROC OglDebugMessageControlARB;
PFNGLDEBUGMESSAGEINSERTARBPROC OglDebugMessageInsertARB;
PFNGLDEBUGMESSAGECALLBACKARBPROC OglDebugMessageCallbackARB;
PFNGLGETDEBUGMESSAGELOGARBPROC OglGetDebugMessageLogARB;
PFNGLGETGRAPHICSRESETSTATUSARBPROC OglGetGraphicsResetStatusARB;
PFNGLGETNTEXIMAGEARBPROC OglGetnTexImageARB;
PFNGLREADNPIXELSARBPROC OglReadnPixelsARB;
PFNGLGETNCOMPRESSEDTEXIMAGEARBPROC OglGetnCompressedTexImageARB;
PFNGLGETNUNIFORMFVARBPROC OglGetnUniformfvARB;
PFNGLGETNUNIFORMIVARBPROC OglGetnUniformivARB;
PFNGLGETNUNIFORMUIVARBPROC OglGetnUniformuivARB;
PFNGLGETNUNIFORMDVARBPROC OglGetnUniformdvARB;
PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC OglDrawArraysInstancedBaseInstance;
PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC OglDrawElementsInstancedBaseInstance;
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC OglDrawElementsInstancedBaseVertexBaseInstance;
PFNGLDRAWTRANSFORMFEEDBACKINSTANCEDPROC OglDrawTransformFeedbackInstanced;
PFNGLDRAWTRANSFORMFEEDBACKSTREAMINSTANCEDPROC OglDrawTransformFeedbackStreamInstanced;
PFNGLGETINTERNALFORMATIVPROC OglGetInternalformativ;
PFNGLGETACTIVEATOMICCOUNTERBUFFERIVPROC OglGetActiveAtomicCounterBufferiv;
PFNGLBINDIMAGETEXTUREPROC OglBindImageTexture;
PFNGLMEMORYBARRIERPROC OglMemoryBarrier;
PFNGLTEXSTORAGE1DPROC OglTexStorage1D;
PFNGLTEXSTORAGE2DPROC OglTexStorage2D;
PFNGLTEXSTORAGE3DPROC OglTexStorage3D;
PFNGLTEXTURESTORAGE1DEXTPROC OglTextureStorage1DEXT;
PFNGLTEXTURESTORAGE2DEXTPROC OglTextureStorage2DEXT;
PFNGLTEXTURESTORAGE3DEXTPROC OglTextureStorage3DEXT;
PFNGLDEBUGMESSAGECONTROLPROC OglDebugMessageControl;
PFNGLDEBUGMESSAGEINSERTPROC OglDebugMessageInsert;
PFNGLDEBUGMESSAGECALLBACKPROC OglDebugMessageCallback;
PFNGLGETDEBUGMESSAGELOGPROC OglGetDebugMessageLog;
PFNGLPUSHDEBUGGROUPPROC OglPushDebugGroup;
PFNGLPOPDEBUGGROUPPROC OglPopDebugGroup;
PFNGLOBJECTLABELPROC OglObjectLabel;
PFNGLGETOBJECTLABELPROC OglGetObjectLabel;
PFNGLOBJECTPTRLABELPROC OglObjectPtrLabel;
PFNGLGETOBJECTPTRLABELPROC OglGetObjectPtrLabel;
PFNGLCLEARBUFFERDATAPROC OglClearBufferData;
PFNGLCLEARBUFFERSUBDATAPROC OglClearBufferSubData;
PFNGLCLEARNAMEDBUFFERDATAEXTPROC OglClearNamedBufferDataEXT;
PFNGLCLEARNAMEDBUFFERSUBDATAEXTPROC OglClearNamedBufferSubDataEXT;
PFNGLDISPATCHCOMPUTEPROC OglDispatchCompute;
PFNGLDISPATCHCOMPUTEINDIRECTPROC OglDispatchComputeIndirect;
PFNGLCOPYIMAGESUBDATAPROC OglCopyImageSubData;
PFNGLTEXTUREVIEWPROC OglTextureView;
PFNGLBINDVERTEXBUFFERPROC OglBindVertexBuffer;
PFNGLVERTEXATTRIBFORMATPROC OglVertexAttribFormat;
PFNGLVERTEXATTRIBIFORMATPROC OglVertexAttribIFormat;
PFNGLVERTEXATTRIBLFORMATPROC OglVertexAttribLFormat;
PFNGLVERTEXATTRIBBINDINGPROC OglVertexAttribBinding;
PFNGLVERTEXBINDINGDIVISORPROC OglVertexBindingDivisor;
PFNGLVERTEXARRAYBINDVERTEXBUFFEREXTPROC OglVertexArrayBindVertexBufferEXT;
PFNGLVERTEXARRAYVERTEXATTRIBFORMATEXTPROC OglVertexArrayVertexAttribFormatEXT;
PFNGLVERTEXARRAYVERTEXATTRIBIFORMATEXTPROC OglVertexArrayVertexAttribIFormatEXT;
PFNGLVERTEXARRAYVERTEXATTRIBLFORMATEXTPROC OglVertexArrayVertexAttribLFormatEXT;
PFNGLVERTEXARRAYVERTEXATTRIBBINDINGEXTPROC OglVertexArrayVertexAttribBindingEXT;
PFNGLVERTEXARRAYVERTEXBINDINGDIVISOREXTPROC OglVertexArrayVertexBindingDivisorEXT;
PFNGLFRAMEBUFFERPARAMETERIPROC OglFramebufferParameteri;
PFNGLGETFRAMEBUFFERPARAMETERIVPROC OglGetFramebufferParameteriv;
PFNGLNAMEDFRAMEBUFFERPARAMETERIEXTPROC OglNamedFramebufferParameteriEXT;
PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVEXTPROC OglGetNamedFramebufferParameterivEXT;
PFNGLGETINTERNALFORMATI64VPROC OglGetInternalformati64v;
PFNGLINVALIDATETEXSUBIMAGEPROC OglInvalidateTexSubImage;
PFNGLINVALIDATETEXIMAGEPROC OglInvalidateTexImage;
PFNGLINVALIDATEBUFFERSUBDATAPROC OglInvalidateBufferSubData;
PFNGLINVALIDATEBUFFERDATAPROC OglInvalidateBufferData;
PFNGLINVALIDATEFRAMEBUFFERPROC OglInvalidateFramebuffer;
PFNGLINVALIDATESUBFRAMEBUFFERPROC OglInvalidateSubFramebuffer;
PFNGLMULTIDRAWARRAYSINDIRECTPROC OglMultiDrawArraysIndirect;
PFNGLMULTIDRAWELEMENTSINDIRECTPROC OglMultiDrawElementsIndirect;
PFNGLGETPROGRAMINTERFACEIVPROC OglGetProgramInterfaceiv;
PFNGLGETPROGRAMRESOURCEINDEXPROC OglGetProgramResourceIndex;
PFNGLGETPROGRAMRESOURCENAMEPROC OglGetProgramResourceName;
PFNGLGETPROGRAMRESOURCEIVPROC OglGetProgramResourceiv;
PFNGLGETPROGRAMRESOURCELOCATIONPROC OglGetProgramResourceLocation;
PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC OglGetProgramResourceLocationIndex;
PFNGLSHADERSTORAGEBLOCKBINDINGPROC OglShaderStorageBlockBinding;
PFNGLTEXBUFFERRANGEPROC OglTexBufferRange;
PFNGLTEXTUREBUFFERRANGEEXTPROC OglTextureBufferRangeEXT;
PFNGLTEXSTORAGE2DMULTISAMPLEPROC OglTexStorage2DMultisample;
PFNGLTEXSTORAGE3DMULTISAMPLEPROC OglTexStorage3DMultisample;
PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC OglTextureStorage2DMultisampleEXT;
PFNGLTEXTURESTORAGE3DMULTISAMPLEEXTPROC OglTextureStorage3DMultisampleEXT;
#endif	// GL_ARB