#ifndef NWGFX_CONSTANT_H
#define NWGFX_CONSTANT_H
#include "nwgfx_core.hpp"
#ifdef NW_GAPI
namespace NWGFX
{
	enum primitives : v1u {
		PRIM_DEFAULT = 0,
		PRIM_POINTS = 1,
		PRIM_LINES,
		PRIM_LINE_LOOP,
		PRIM_LINE_STRIP,
		PRIM_TRIANGLES,
		PRIM_TRIANGLE_STRIP,
		PRIM_TRIANGLE_FAN,
	};
	enum fill_modes : v1u {
		FILL_DEFAULT = 0,
		FILL_LINE,
		FILL_FACE,
	};
	enum cull_modes : v1u {
		CULL_DEFAULT = 0,
		CULL_CW,
		CULL_CCW,
	};
	enum blend_factors : v1u {
		BLEND_SRC_DEFAULT = 0,
		BLEND_DST_DEFAULT = 0,
		BLEND_SRC_ALPHA,
		BLEND_DST_ALPHA,
		BLEND_SRC_COLOR,
		BLEND_DST_COLOR,
		BLEND_ONE_MINUS_SRC_ALPHA,
		BLEND_ONE_MUNUS_DST_ALPHA,
		BLEND_ONE_MINUS_SRC_COLOR,
		BLEND_ONE_MINUS_DST_COLOR,
	};
	enum stencil_opers : v1u {
		STENC_DEFAULT = 0,
		STENC_INCR,
		STENC_DECR,
		STENC_KEEP,
		STENC_ZERO,
		STENC_REPL,
		STENC_INVERT,
	};
	enum texture_wraps : v1u {
		TXW_DEFAULT = 0,
		TXW_REPEAT,
		TXW_CLAMP,
		TXW_BORDER,
	};
	enum texture_filters : v1u {
		TXFL_DEFAULT = 0,
		TXFL_LINEAR,
		TXFL_NEAREST,
	};
	enum texture_formats : v1u {
		TXF_DEFAULT = 0u,
		TXF_RGB,
		TXF_RGBA,
		TXF_MONO,
		TXF_IDX,
		TXF_DEPTH,
		TXF_STENCIL,
		TXF_DEPTH_STENCIL,
	};
	enum pixel_formats : v1u {
		PXF_DEFAULT = 0,
		PXF_R8_S8, PXF_R8_U8,
		PXF_R16_S16, PXF_R8G8_S16,
		PXF_R16_U16, PXF_R8G8_U16,
		PXF_R32_S32, PXF_R16G16_S32,
		PXF_R8G8B8_S32, PXF_R8G8B8A8_S32,
		PXF_R32_U32, PXF_R16G16_U32,
		PXF_R8G8B8_U32, PXF_R8G8B8A8_U32,
		PXF_S8_S8, PXF_D32_S32,
		PXF_S8_U8, PXF_D32_U32,
		PXF_D24S8_S32, PXF_D24S8_U32,
	};
}
#endif	// NW_GAPI
#endif	// NWGFX_CONSTANT_H